### ISSUE TITLE
Breaks with bootstrap 4.0.0-beta

### ISSUE THREAD

**Issue by amikhalev** [reactstrap/reactstrap#545] opened 2017-08-15 21:56 UTC
### Issue description

- version `#4.8.0`

### Steps to reproduce issue

* `Dropdown` no longer works, because the `.dropdown-menu` element needs the `show` style when it is open
* `Navbar` styles have changed. It is now `navbar-expandable` instead of `navbar-toggleable`
* `CardBlock` should now be `CardBody` with the `card-body` class
* Buttons by default should be `btn-default`, not `btn-secondary` because the style for `btn-secondary` has changed

Along with other things I'm sure I haven't caught

**Comment by TheSharpieOne** [comment] 2017-08-15 22:44
Duplicate of #487

**Closed** 2017-08-16 05:13 UTC
