### ISSUE TITLE
Cards overlapping reactstrap modal

### ISSUE THREAD

**Issue by WilfredKesh** [reactstrap/reactstrap#1300] opened 2018-11-20 16:14 UTC
```
- reactstrap version `^5.0.0`
- react version `^16.3.2`
```

I am using a reactstrap modal but the reactstrap Cards are overlapping the modal in certain computers in IE 11. Is there a way to fix this.  

I figured the issue is related to nested divs z-index's where the parent div's z-index is overriding the modal's z-index.  

I came up with a hack that fixes the problem. 

```
  removeIndex() {
    const focusable = document.querySelectorAll(' [tabindex="-1"]');
    focusable[0].style.zIndex = '0';
  }
```

The problem is how do I know when the modal has loaded to invoke the removeIndex function? The modal data is loaded by a data from a service call from a mobx store.

Is there a callback function that is triggered when the modal is open?

Is there a cleaner way of fixing the error?

Thanks.

**Comment by TheSharpieOne** [comment] 2018-11-20 16:58
Can you provide a screenshot or demo code (including any custom styles/css) or even a live exmple via something like https://stackblitz.com/edit/reactstrap-v5?file=Example.js

**Comment by Davidhervil** [comment] 2019-01-01 17:57
I'm Having the same issue with Chrome

**Comment by GoPro16** [comment] 2020-02-26 05:58
Closing this issue as it seems to be a user error, feel free to re-open if you are still running into issues and post a reproducible stackblitz or codesandbox.

**Closed by GoPro16** 2020-02-26 05:58 UTC
Labels: needs example/more info
