### ISSUE TITLE
Size of a modal

### ISSUE THREAD

**Issue by AlbertoCalvo** [reactstrap/reactstrap#595] opened 2017-09-27 20:41 UTC
How can I change the size of a modal ?. I think it can be done with the 'size' property, but what kind of 'string' should be set.

**Comment by AlbertoCalvo** [comment] 2017-09-27 21:14
I had not tried with "lg". It works well. And bigger?

**Comment by TheSharpieOne** [comment] 2017-09-27 21:17
The same kind of string bootstrap would expect, just without the prefix. In this case `"lg"` or `"sm"` (as their classes are `.modal-lg` and `.modal-lg` respectfully) https://getbootstrap.com/docs/4.0/components/modal/#optional-sizes 
Most of the components work that way since the prefix is known and there is no need to use it, such as `color` for Button is `"primary"` instead of `"btn-primary"`. This also allows you to extend bootstrap to add your own variations, like maybe "`xl"` for the modal size and it will produce `.modal-xl` which follows the bootstrap naming convention.

**Comment by TheSharpieOne** [comment] 2017-10-31 11:48
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2017-10-31 11:48 UTC
Labels: question

**Comment by Vadorequest** [comment] 2017-11-28 15:16
Please improve the documentation at https://reactstrap.github.io/components/modals/ to make this more obvious.

**Comment by TheSharpieOne** [comment] 2017-11-28 17:26
It's less specific to modal than it is to reactstrap as a whole and how it uses bootstrap variants. It should be documented, but somewhere generic similar to documentation about `tag`

**Comment by Vadorequest** [comment] 2017-11-28 19:10
Just an exemple would be enough, or a link to the generic explanation
regarding sizes.

**Comment by DmitryGG** [comment] 2018-03-03 17:45
On `<Modal />` component set `size="lg"` or what you need, and it works. But in docs it really bat explained.

**Comment by atuljustano** [comment] 2018-11-28 12:14
I am trying for extra large but it not works (**modal-xl**)

**Comment by TheSharpieOne** [comment] 2018-11-29 00:36
xl is not a standard/default available size. You'd need custom styles.
You can extend bootstrap's css easily to add this, check out bootstrap's docs for information on how to best do that.

**Comment by vklap** [comment] 2019-05-25 18:58
On the Modal component, you can set an inline style like so:

`
<Modal size="lg" style={{maxWidth: '1600px', width: '80%'}}>
...
</Modal>
`

**Comment by novonimo** [comment] 2019-10-08 08:48
> On the Modal component, you can set an inline style like so:
> 
> `<Modal size="lg" style={{maxWidth: '1600px', width: '80%'}}> ... </Modal>`

َUnfortunetly it doesn't work. the only size will work.
none of style or className, style or modalClassName will work

**Comment by TheSharpieOne** [comment] 2019-10-08 15:41
@novonimo it works: https://stackblitz.com/edit/reactstrap-v8-26fhei?file=Example.js (make your browser wide and see that the modal keeps getting expanding)

**Comment by ELI7VH** [comment] 2020-10-19 23:12
This should work with classNames. We shouldn't need to override with the inline `style` property or having to use !important. It seems like some inline style needs to be removed on the modal generator code.

**Comment by milan2you** [comment] 2020-12-11 19:13
@novonimo it works: https://stackblitz.com/edit/reactstrap-v8-26fhei?file=Example.js (make your browser wide and see that the modal keeps getting expanding)
This works for me Thanx

**Comment by EarvinJay** [comment] 2021-07-30 03:49
> > On the Modal component, you can set an inline style like so:
> > `<Modal size="lg" style={{maxWidth: '1600px', width: '80%'}}> ... </Modal>`
> 
> َUnfortunetly it doesn't work. the only size will work.
> none of style or className, style or modalClassName will work

You can use className instead. For example:  className={ max-width: 80%; max-height: 80%; }

**Comment by doverradio** [comment] 2021-11-19 19:54
So, I have noticed that despite importing a custom style sheet which imports a class I made named `custom-modal-style`, using `contentClassName` to display the styles, and rendering the Modal, it does apply the style but not consistently.  What I mean is even when I see the modal nearly fill up the entire screen, when I refresh the page and reload the same modal it fails to apply the new style sizes.  Here's what I am using as my stylesheet, maybe you can see what I'm doing wrong...

```
    .custom-modal-style {
      position: fixed;
      left: 5px;
      width: 98%;
      right: 5px;
      max-height: 100%;
      overflow: auto;
      overflow-y: scroll;
      display: block;
  }
```

The above is then set as a class name in `contentClassName` like so...
```
<Modal size="xl" isOpen={modal} toggle={toggle} contentClassName="custom-modal-style">...</Modal>
```
Literally only applies special size upon saving during development.  After, it never applies `custom-modal-style` and I don't know why.  Help please!
