### ISSUE TITLE
offsets 

### ISSUE THREAD

**Issue by arpecop** [reactstrap/reactstrap#586] opened 2017-09-22 14:09 UTC
offsets are removed in bootstrap 4, I hope this and other changes will reflect on documentation soon. Thanks

**Comment by TheSharpieOne** [comment] 2017-09-22 14:13
Last I heard they were adding them back in beta 2

**Comment by HamadaBrest** [comment] 2017-10-26 11:02
**offset** doesn't work for me too... how we can center an element ?

**Comment by TheSharpieOne** [comment] 2017-10-26 11:21
You can use the flexbox utilities bootstrap provides.
Currently, because any and every component can have those utilities, you'll have to just apply the className directly; there isn't a nice baked in prop to do so (yet?).

**Comment by HamadaBrest** [comment] 2017-10-26 11:23
@TheSharpieOne Thank you

**Comment by sabbakeynejad** [comment] 2017-10-27 11:12
I think this problem might be due to conflicting versions of bootstrap and react strap. The below setup worked for me.

`npm install bootstrap@4.0.0-alpha.6 --save`

And then import it into your project.

`import 'bootstrap/dist/css/bootstrap.css';`

Then add reactstrap.

`npm install --save reactstrap@next react@^16.0.0 react-dom@^16.0.0`

**Comment by TheSharpieOne** [comment] 2017-10-31 11:51
reactstrap@next which is currently the reactstrap v5 alpha is meant to be used with bootstrap v4-beta (and works fairly well with bootstrap v4-beta.2), not bootstrap v4.0.0-alpha.6

**Comment by TheSharpieOne** [comment] 2017-11-21 11:08
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2017-11-21 11:08 UTC
