### ISSUE TITLE
grid system: missing reordering props

### ISSUE THREAD

**Issue by landsman** [reactstrap/reactstrap#1576] opened 2019-07-14 17:34 UTC
- components: `Col`
- reactstrap version `#8.0.1`
- bootstrap version `#4`

For me missing this part of grid system in properties of `Col` component.
I have to write this to `className` which is not transparent so much.

https://getbootstrap.com/docs/4.0/layout/grid/#reordering

**Comment by nylon22** [comment] 2019-10-17 19:05
`reactstrap` does support reordering props. See
- https://github.com/reactstrap/reactstrap/blob/master/src/Col.js#L15
- https://github.com/reactstrap/reactstrap/blob/master/src/Col.js#L74

Can you link a code sandbox demonstrating the issue?

**Comment by TheSharpieOne** [comment] 2019-12-10 15:44
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2019-12-10 15:44 UTC
