### ISSUE TITLE
Getting a selection from the ButtonDropdown/DropdownItem Component

### ISSUE THREAD

**Issue by JeffWScott** [reactstrap/reactstrap#559] opened 2017-08-29 18:49 UTC
- version `0.31.1`
- components: `ButtonDropdown`

### Steps to reproduce issue
`<ButtonDropdown isOpen={this.state.dropdownOpen} toggle={this.toggle}>`
`    <DropdownToggle caret size="lg"> THINGS </DropdownToggle>`
`    <DropdownMenu>`
`        {this.state.thingList.map(thing=>`
`            <DropdownItem>{thing}</DropdownItem>`
`        )}`
`    </DropdownMenu>`
`</ButtonDropdown>`

I don't understand how to use this ButtonDropdown to get the value that is selected.  I can display and populate the list with no issues, but cannot figure out how to action off a selected item.  The webpage just says "Action", "Another Action" etc, but nothing on how to handle a click.

I tried 
`<DropdownItem onClick({this.handleClick})>{thing}</DropdownItem>` 
but that fires when each item is instantiated and whenever the dropdown is toggled; so that can't be right.

Can someone please help me understand?

**Comment by TheSharpieOne** [comment] 2017-08-29 18:53
Duplicate of #372

**Comment by JeffWScott** [comment] 2017-08-29 19:04
Please don't close.  The case you attached doesn't solve my problem.

Are you suggesting that I need to put a <div> tag in between the <DropdownItem> tags with an onClick event?  That seems strange.  Also, I tried it and it doesn't work as well.

**Comment by TheSharpieOne** [comment] 2017-08-29 19:19
Checking the markup from that other issue to use the standard reactstrap components I get: https://www.webpackbin.com/bins/-KsjQHBezRxzZgyWWRIv

```jsx
import React from 'react';
import { Container, ButtonDropdown, DropdownMenu, DropdownItem, DropdownToggle } from 'reactstrap';

class ReactstrapExample extends React.Component {
  constructor(props) {
    super(props);
    this.toggle = this.toggle.bind(this);
    this.select = this.select.bind(this);
    this.state = {
      dropdownOpen: false,
      value : "Home"
    };
  }
  
  toggle() {
    this.setState({
      dropdownOpen: !this.state.dropdownOpen
    });
  }

  select(event) {
    this.setState({
      dropdownOpen: !this.state.dropdownOpen,
      value: event.target.innerText
    });
  }
  
  render() {
    return (
      <Container className="py-4">
        <ButtonDropdown isOpen={this.state.dropdownOpen} toggle={this.toggle}>
        <DropdownToggle>{this.state.value}</DropdownToggle>
        <DropdownMenu>
          <DropdownItem onClick={this.select}>Work</DropdownItem>
          <DropdownItem onClick={this.select}>Contact</DropdownItem>
        </DropdownMenu>
      </ButtonDropdown>
      </Container>
    );
  }
}
export default ReactstrapExample
```

**Comment by TheSharpieOne** [comment] 2017-09-15 22:30
@JeffWScott did the above answer your question?

**Comment by JeffWScott** [comment] 2017-09-15 22:38
Honestly, i went a different way, i couldn't get it to work.

My solution was super clunky but actually worked.
________________________________

**Closed** 2017-09-15 22:39 UTC

**Comment by impactcolor** [comment] 2019-12-12 16:35
What @JeffWScott meant to say but he forgot since he got so busy was, "THANK YOU FOR ATTEMPTING TO HELP ME AND FOLLOWING UP" @TheSharpieOne
