### ISSUE TITLE
Not working with react 16.0.0

### ISSUE THREAD

**Issue by Rootmafia** [reactstrap/reactstrap#605] opened 2017-10-02 21:12 UTC
## **Issue description**

- version 4.8.0
- components: Modal

I updgraded react version to "16.0.0"   and reactstrap  is not working now.
When i was using older version of reactstrap,  it was failing on React.PropTypes as PropTypes where moved in separate package.
 In  ( "reactstrap": "^4.8.0") **I'm getting:**

`   reactstrap.cjs.js:2433 Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at Modal.renderIntoSubtree (reactstrap.cjs.js:2433)
    at Modal.show (reactstrap.cjs.js:2399)
    at Modal.togglePortal (reactstrap.cjs.js:2353)
    at Modal.componentDidMount (reactstrap.cjs.js:2285)
    at commitLifeCycles (react-dom.development.js:11505)
    at commitAllLifeCycles (react-dom.development.js:12294)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
    at invokeGuardedCallback (react-dom.development.js:1195)
    at commitAllWork (react-dom.development.js:12415)
`

**It is Failing on :** 

`    
      // check if modal should receive focus
      if (this._focus) {
          this._dialog.parentNode.focus();  // << _this.__dialog  is undefined_
          this._focus = false;
      }

`

**Comment by TheSharpieOne** [comment] 2017-10-02 21:24
Duplicate of #532

There is a pre-release which addresses this issue (use `npm i reactstrap@next`) by avoiding the focus, but I am hoping that the work being done for #601 will address this issue in a better way allowing the focus to work with R16.

**Closed by TheSharpieOne** 2017-10-02 21:24 UTC

**Comment by Rootmafia** [comment] 2017-10-02 21:39
Modal is working now, but starts failing on  Dropdown,  i'm getting: 

`popper.js:2325 Uncaught TypeError: Cannot read property 'jquery' of undefined
    at new Popper (popper.js:2325)
    at Popper._createPopper (Popper.js:173)
    at Popper._updatePopper (Popper.js:152)
    at Popper.componentDidMount (Popper.js:129)
    at commitLifeCycles (react-dom.development.js:11505)
    at commitAllLifeCycles (react-dom.development.js:12294)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
    at invokeGuardedCallback (react-dom.development.js:1195)
    at commitAllWork (react-dom.development.js:12415)`

and +

`react-dom.development.js:8305 The above error occurred in the <Popper> component:
    in Popper (created by DropdownMenu)
    in DropdownMenu (at Header.js:61)
    in div (created by Manager)
    in Manager (created by Dropdown)
    in Dropdown (at Header.js:52)
    in li (at Header.js:51)
    in ul (at Header.js:50)
    in header (at Header.js:35)
    in Header (created by Connect(Header))
    in Connect(Header) (created by Route)
    in Route (created by withRouter(Connect(Header)))
    in withRouter(Connect(Header)) (at HomeContainer.js:19)
    in div (at HomeContainer.js:18)
    in Home (created by Connect(Home))
    in Connect(Home) (at WrapHome.js:7)
    in WrapHome (at Menu.js:26)
    in main (at PrivateRoute.js:11)
    in Route (at PrivateRoute.js:6)
    in PrivateRoute (at App.js:34)
    in Switch (at App.js:32)
    in div (at App.js:30)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:28)
    in App (created by Connect(App))
    in Connect(App) (at index.js:14)
    in Provider (at index.js:13)`

**Comment by TheSharpieOne** [comment] 2017-10-02 21:54
Can you open a new ticket for this new issue. Also can you include a minimum sample code to reproduce the issue. You can use something like webpackbin.com or codesandbox.com to enable a live demo showcasing your issue.
From the error, it looks like `DropdownToggle` was not used within `Dropdown` or for some reason the `Target` was not set when the `Popper` (via react-popper) was mounted.
The error itself is coming from popper.js, it looks like it was [fixed a little while ago](https://github.com/FezVrasta/popper.js/commit/04337931428351d9346d4a8963e28d7fed3a33b6) but has [not been released yet](https://github.com/FezVrasta/popper.js/compare/v1.12.5...master). Though the error being fix in popper.js probably doesn't really fix your issue if the `target` is not set in react-popper.
Anyways, open a new issue and provide some code to reproduce the issue and I'll take a look at it.
