### ISSUE TITLE
Modal not closing when backdrop is tapped

### ISSUE THREAD

**Issue by ted-lee** [reactstrap/reactstrap#365] opened 2017-03-17 14:44 UTC
### Issue description

- version `#4.3.0`
- components: `Modals`
- device: iphone (iOS 9.3.5), only occurs in iphone browsers (no matter the browser is Chrome or Safari)
- the same issue had been fixed in react-bootstrap before: https://github.com/react-bootstrap/react-bootstrap/issues/150

### Steps to reproduce issue
- open the sample https://reactstrap.github.io/components/modals/
- launch a modal that has a backdrop
- tap the backdrop to close the modal, not working

**Comment by shaaslam** [comment] 2017-04-03 15:30
Unable to reproduce on iPhone6 (iOS 10.3) Safari.

**Comment by eddywashere** [comment] 2017-04-03 16:18
Thanks for the info! I was pretty sure I also was able to do this on a recent IOS version. It would be good to isolate the versions affected and whether bootstrap v4 supports those versions of browsers to prioritize this.

**Comment by ted-lee** [comment] 2017-04-05 09:31
I encounter the problem in following devices:
(1) iphone 5s (iOS 9.3.5) safari & chrome

**Comment by marcnjaramillo** [comment] 2019-12-03 03:09
This is an older issue that hasn't been addressed yet. I pulled up the modal component on my iPhone X (iOS 13.1.3) and when the backdrop is set to "true", I am able to close out the modal by clicking anywhere else on the screen. When it is set to "false" or "static", I am unable to do this and am forced to close by clicking one of the buttons. This doesn't seem to be an issue anymore. Can it be closed?

**Comment by TheSharpieOne** [comment] 2019-12-10 02:00
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2019-12-10 02:00 UTC
Labels: PR Welcome, bug, help wanted, up-for-grabs
