### ISSUE TITLE
Examples of create-react-app + reactstrap + sass customized?

### ISSUE THREAD

**Issue by bhellman1** [reactstrap/reactstrap#643] opened 2017-10-19 15:24 UTC
Hello, I'm using facebook's create-react-app with Sass and have been unable customize reactstrap within (create-react-app + reactstrap + sass).

Are there any example apps available showing how to customize reactstrap within facebook's create-react-app with Sass?

Thanks

**Comment by TheSharpieOne** [comment] 2017-10-19 15:30
Without ejection: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc
With ejection: https://medium.com/@Connorelsea/using-sass-with-create-react-app-7125d6913760

**Comment by TheSharpieOne** [comment] 2018-03-30 17:06
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2018-03-30 17:06 UTC
