### ISSUE TITLE
Popover 'bottom right' placement issue

### ISSUE THREAD

**Issue by jonnyojonny** [reactstrap/reactstrap#501] opened 2017-07-16 08:47 UTC
### Issue description
Hey team, could you please check 'bottom right' ('bottom left') placements for the Popover component. Arrow between popover and target looks broken! Can i fix it somehow without diving into the sources? Thanks in advance!

### Steps to reproduce issue
https://codepen.io/anon/pen/MoRemW

- version 
  "react": "^15.3.0",
   "react-dom": "^15.3.0",
   "react-transition-group": "^1.1.2",
   "reactstrap": "^4.8.0"
   "bootstrap": "^4.0.0-alpha.6"
- components: Popover

**Comment by stefan-schweiger** [comment] 2017-07-17 10:41
Duplicate of https://github.com/reactstrap/reactstrap/issues/114

**Comment by TheSharpieOne** [comment] 2017-07-25 19:04
Closing as duplicate of #114. Please use the original issue to track the status.

**Closed by TheSharpieOne** 2017-07-25 19:04 UTC

**Comment by TheSharpieOne** [comment] 2017-07-25 19:06
Closing as duplicate of #114. Please use the original issue to track the status.
