### ISSUE TITLE
Dropdown not displaying

### ISSUE THREAD

**Issue by jlsorak** [reactstrap/reactstrap#648] opened 2017-10-21 19:55 UTC
### Issue description

- components: `ButtonDropdown, DropdownToggle, DropdownMenu, DropdownItem`
- reactstrap version `#4.8.0`
- react version `#15.4.2`
- bootstrap version `#4.0.0-beta.2`

### What is happening?
The dropdown menu isn't displaying correctly, it doesn't open when pressing the button. http://recordit.co/suzk71KO9F

I have react-popper installed too, but doesn't make a difference. 

I'm using the dropdown just like the examples in the docs: 

```
import React from 'react';
import { ButtonDropdown, DropdownToggle, DropdownMenu, DropdownItem } from 'reactstrap';

class Header extends React.Component {
  constructor() {
    super();
    
    this.toggle = this.toggle.bind(this);
    this.state = {
      dropdownOpen: false
    }
  }
  
  toggle() {
    this.setState({
      dropdownOpen: !this.state.dropdownOpen
    })
  }
  
  render() {
    return (
      <div className="nav">
        <div>
              <ButtonDropdown isOpen={this.state.dropdownOpen} toggle={this.toggle}>
                <DropdownToggle caret>
                  Button Dropdown
                </DropdownToggle>
                <DropdownMenu>
                  <DropdownItem disabled>
                    <div>
                      <h1>test</h1>
                    </div>
                  </DropdownItem>
                  <DropdownItem>Another Action</DropdownItem>
                  <DropdownItem divider />
                  <DropdownItem>Another Action</DropdownItem>
                </DropdownMenu>
              </ButtonDropdown>
        </div>
      </div>
    )
  }  
}

export default Header
```

### Error message in console
Not receiving any errors in the console, apart from the usual tether warnings.

**Comment by TheSharpieOne** [comment] 2017-10-21 22:57
Duplicate of #581
Duplicate of #549
Duplicate of #569
Duplicate of #545
Duplicate of #588
Duplicate of #596

Use v5 by installing with `@next`

**Closed** 2017-10-21 22:58 UTC
Labels: duplicate

**Comment by nbeuchat** [comment] 2018-04-24 18:24
This solution did not work for me. 

- components: `ButtonDropdown`, `DropdownToggle`, `DropdownMenu`, `DropdownItem`
- reactstrap version `#5.0.0-beta.3`
- react version `#16.2.0`
- bootstrap version `#4.1.0`

**Comment by TheSharpieOne** [comment] 2018-04-24 20:11
This issue is old, reactstrap version 5.0.0 has been released.
See https://stackblitz.com/edit/reactstrap-v5-bhwntx?file=Example.js
