### ISSUE TITLE
How to set options globally?

### ISSUE THREAD

**Issue by ahalimkara** [reactstrap/reactstrap#484] opened 2017-06-29 13:45 UTC
### Issue description

- version `#4.8.0`
- components: `tooltip`

I would like to set delay.hide property globally for tooltips to 0 instead of setting in every tooltip component. Is it possible?
`delay: PropTypes.oneOfType([
    PropTypes.shape({ show: PropTypes.number, hide: PropTypes.number }),
    PropTypes.number
  ])`

PS:
Since early versions of Bootstrap, the default delay is always 0. So i don't understand why it is 250ms for reactstrap. I feel like the page works slow when it has delay on hide.

**Comment by TheSharpieOne** [comment] 2017-06-29 14:24
Perhaps the default should be `0` to match what bootstrap's is. Other than that, you can create a wrapper component which will default values for you.
```
import {Tooltip} from 'reactstrap';
export default function MyTooltip(props) {
  return <Tooltip delay={0} {...props} />
}
```

**Comment by TheSharpieOne** [comment] 2017-07-27 02:51
@ahalimkara did this answer your question?

**Comment by ahalimkara** [comment] 2017-07-28 07:37
@TheSharpieOne thank you for your answer, yea it answers my question however i thought maybe core developers will consider to make default values same with bootstrap's defaults. Thanks again and sorry for late reply.

**Comment by TheSharpieOne** [comment] 2017-07-28 20:39
I believe the default delay was to match the animation duration since the animation is true by default for bootstrap. Since there was no way to control the animation in reactstrap (which is another thing that doesn't line up with bootstrap) it was probably a compromise.
I made a PR to default hide to 0 and add animation and a way to control the animation. This should satisfy this issue

**Comment by TheSharpieOne** [comment] 2018-03-30 17:17
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2018-03-30 17:17 UTC
