### ISSUE TITLE
Browser has crashed when use Popover component

### ISSUE THREAD

**Issue by thanhmu** [reactstrap/reactstrap#1637] opened 2019-10-03 04:38 UTC
- components: `PopperContent.js`
- reactstrap version `#8.0.0`
- import method `umd/csj/es` 
- react version `#16.3.0`
- bootstrap version `#4.3.1`

### What is happening?

Browser has crashed when I use Google chrome developer tools+ component PopperContent.

### What should be happening?

When I using Popover and turn on developer tools browser, browse has crashed when i resize developer tool over Popover component with status open.
![Screenshot from 2019-10-03 11-36-43](https://user-images.githubusercontent.com/12042228/66099787-5eed1780-e5d2-11e9-809a-9476ce7d199b.png)

**Comment by TheSharpieOne** [comment] 2019-10-03 12:48
Duplicate of #1488
Duplicate of #1482

**Closed by TheSharpieOne** 2019-10-03 12:48 UTC
