### ISSUE TITLE
Popover prop type warning when upgrading to 8.8.0

### ISSUE THREAD

**Issue by sudravi** [reactstrap/reactstrap#2060] opened 2020-12-28 23:45 UTC
- components: `Popover`
- reactstrap version `#8.8.0`
- import method `es`
- react version `#17.0.1`
- bootstrap version `#4.3.1`

### What is happening?

Getting warning message for basic popover

### What should be happening?

Warning message wasn't there prior to 8.8.0

### Steps to reproduce issue

1. Run this CodeSandbox: https://codesandbox.io/s/reactstrap-popover-forked-28dd8

### Error message in console

Warning: Failed prop type: The prop `target` is marked as required in `PopperContent`, but its value is `undefined`.
    in PopperContent (created by TooltipPopoverWrapper)
    in TooltipPopoverWrapper (created by Popover)
    in Popover (at src/index.js:30)
    in div (at src/index.js:26)
    in Example (at src/index.js:50)

### Code

See CodeSandbox link above

**Comment by kyletsang** [comment] 2020-12-29 02:21
Dupe of #2058

**Closed by kyletsang** 2020-12-29 02:21 UTC
Labels: duplicate
