### ISSUE TITLE
navbar react in laravel

### ISSUE THREAD

**Issue by toeurtenh** [reactstrap/reactstrap#1478] opened 2019-04-30 15:48 UTC
I just want a navbar for my react in laravel

I've tried bootstrap

            <nav className="navbar navbar-expand-lg navbar-light bg-light">
                <a className="navbar-brand" href="#">Navbar</a>
                <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarNav">
                    <ul className="navbar-nav">
                        <li className="nav-item active">
                            <a className="nav-link" href="#">Home <span className="sr-only">(current)</span></a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link" href="#">Features</a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link" href="#">Pricing</a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                        </li>
                    </ul>
                </div>
            </nav> 

and also reactstrap by following https://reactstrap.github.io/components/navbar/

     <div>
        <Navbar color="light" light expand="md">
          <NavbarBrand href="/">reactstrap</NavbarBrand>
          <NavbarToggler onClick={this.toggle} />
          <Collapse isOpen={this.state.isOpen} navbar>
            <Nav className="ml-auto" navbar>
              <NavItem>
                <NavLink href="/components/">Components</NavLink>
              </NavItem>
              <NavItem>
                <NavLink href="https://github.com/reactstrap/reactstrap">GitHub</NavLink>
              </NavItem>
              <UncontrolledDropdown nav inNavbar>
                <DropdownToggle nav caret>
                  Options
                </DropdownToggle>
                <DropdownMenu right>
                  <DropdownItem>
                    Option 1
                  </DropdownItem>
                  <DropdownItem>
                    Option 2
                  </DropdownItem>
                  <DropdownItem divider />
                  <DropdownItem>
                    Reset
                  </DropdownItem>
                </DropdownMenu>
              </UncontrolledDropdown>
            </Nav>
          </Collapse>
        </Navbar>
      </div>

But the style doesn't apply (see image), why? how do I get a navbar in easy way?

![errow](https://user-images.githubusercontent.com/8510436/56975255-50ed2380-6b68-11e9-813c-b3ae3d210578.png)

- components: `name`
- reactstrap version `#x.x.x`
- import method `umd/csj/es` 
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by TheSharpieOne** [comment] 2019-04-30 16:02
It doesn't looks like bootstrap is loading. Make sure you are including at least bootstrap v4. Also, take a look at https://laravel.com/docs/5.8/mix#sass (or https://laravel.com/docs/5.8/mix#plain-css) and maybe even https://laravel.com/docs/5.8/mix#copying-files-and-directories

**Comment by toeurtenh** [comment] 2019-04-30 20:24
Loading bootstrap I use import 'bootstrap/dist/css/bootstrap.min.css'; as you recommanded

**Comment by toeurtenh** [comment] 2019-04-30 21:40
I've got like picture below after update bootstrap 3 to 4

![error2](https://user-images.githubusercontent.com/8510436/56995152-d983b800-6b98-11e9-9914-a9b3d6c5933c.png)

but it is not what I want. I want like this

![answer](https://user-images.githubusercontent.com/8510436/56995179-eaccc480-6b98-11e9-8196-9f8480775af6.png)

**Comment by TheSharpieOne** [comment] 2019-05-01 13:54
> when i code like this import 'bootstrap/dist/css/bootstrap-v4.min.css';
does it link to node_modules/bootstrap/dist/css/bootstrap-v4.min.css ?

This depends on your build tool. If you were using CRA I would say yes, but with laravel I don't know. I saw something in the laravel docs about having to copy assets/files from node_modules to a public directory, you may need to do that.

> Do I need to import only css how about bootstrap.js?

Correct, reactstrap's components replaces the need for bootstrap.js (and jquery)

I seems like something is still wrong with the styles. I would suggest opening an issue with laravel since in the example you posted you were not even using reactstrap's components (you were using HTML elements with className directly) and it still didn't work.

Here is your example, but without laravel and everything works: https://stackblitz.com/edit/reactstrap-v8-qg6kwh?file=Example.js

**Comment by toeurtenh** [comment] 2019-05-07 10:15
@TheSharpieOne 
it's a good idea to opena issue with laravel, do you know the link to laravel?

**Comment by TheSharpieOne** [comment] 2019-05-07 16:13
https://laracasts.com/discuss

**Comment by TheSharpieOne** [comment] 2019-12-10 15:48
I'm closing this since the the issue is no longer active. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2019-12-10 15:48 UTC
