### ISSUE TITLE
inNavbar, addonType... error

### ISSUE THREAD

**Issue by dev-ys** [reactstrap/reactstrap#770] opened 2018-01-06 12:26 UTC
help me

```
Warning: React does not recognize the `inNavbar` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `innavbar` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

```
Warning: React does not recognize the `addonType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `addontype` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

reactstrap version 5.0.0-alpha.4
bootstrap version 4.0.0-beta.3

**Comment by asliwinski** [comment] 2018-01-09 02:59
Same problem + the input group is not styled correctly:

![image](https://user-images.githubusercontent.com/14044823/34703095-717e257a-f4f1-11e7-9925-75aa134fea74.png)

**Comment by dev-ys** [comment] 2018-01-09 03:09
You can find the issue by following.
If I install the latest version, it appears that reactstrap version5.00-alpha.4 is successfully installed but the inNavbar & addonType component are missing.

I guess the previous version is messed up with the latest one as I am able to find these components from cloned source.

**Comment by asliwinski** [comment] 2018-01-09 03:29
The following workaround works for me:

```
<InputGroup>
  <InputGroupAddon className='input-group-prepend'>
    <span className='input-group-text'>@</span>
  </InputGroupAddon>
  <Input placeholder='username' />
</InputGroup>
```

**Comment by TheSharpieOne** [comment] 2018-01-09 13:58
The reactstrap changes which correlate with bootstrap beta.3 have not been released yet (no release has been created since the changes have been merged)

**Comment by BobWalsh** [comment] 2018-01-10 01:28
Getting the same thing using the Navbar code example:
`index.js:2177 Warning: React does not recognize the `inNavbar` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `innavbar` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

Is there a workaround for the NavBar?

**Comment by dev-ys** [comment] 2018-01-10 01:43
I resolved this problem as follows.

-  clone git (v5.0.0-alpha.4)
-  build reactstrap on local
-  copy dist and lib folder to /node_modules/reactstrap (replace)
All work well

**Comment by smonff** [comment] 2018-01-19 11:50
Upgrading `reactstrap` from `4.8.0` to `5.0..0-alpha.4` helped.

**Closed** 2018-01-27 00:09 UTC
Labels: not a bug

**Comment by hbj** [comment] 2018-01-27 19:15
I confirm that building reactstrap from source and without any modifications resolves the navbar issue (I didn't test the other ones), so it seems to be just a build issue.

**Comment by monbro** [comment] 2018-01-28 08:48
I am having the same issue with the latest version of today.

**Comment by supergibbs** [comment] 2018-01-28 16:09
The issue is that the docs are based on the latest code not latest release. The latest release is best compatible with `BS4-beta.2`. A new release should be soon, but in the meantime, you can build the latest locally and use that like @dev-ys did: https://github.com/reactstrap/reactstrap/issues/770#issuecomment-356472250
