### ISSUE TITLE
Update the version of react-popper to 0.7.4

### ISSUE THREAD

**Issue by gauravshahhere** [reactstrap/reactstrap#676] opened 2017-11-09 21:01 UTC
### Issue description

- components: `react-popper`
- reactstrap version `5.0.0-alpha.3`

### What is happening?

keep seeing the warnings for react-popper because the current version that is pulled in by reactstrap does not have updated peer dependencies for react 16

### What should be happening?

react-popper just came out with a new version (0.7.4) and that has the updated peer dependencies to support react 16 and once reactstrap pulls that updated version the warnings should go away.

### Error message in console

```
warning "react-popper@0.7.3" has incorrect peer dependency "react@0.14.x || ^15.0.0".
warning "react-popper@0.7.3" has incorrect peer dependency "react-dom@0.14.x || ^15.0.0"
```

**Comment by TheSharpieOne** [comment] 2017-11-09 21:31
The version in the peerDeps allows for anything above 0.7.3 and below 1.0.0. Check your package.json to make sure you have not pinned the version and do an npm update.

**Comment by TheSharpieOne** [comment] 2017-11-21 10:37
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2017-11-21 10:37 UTC
