### ISSUE TITLE
Modal call blocks and removes scrolls on parent window

### ISSUE THREAD

**Issue by wzup** [reactstrap/reactstrap#164] opened 2016-10-01 07:23 UTC
An example is your modal demo https://reactstrap.github.io/components/modals/
Call modal (click "Launch Modal" button) , then close the modal (click "Do Something" or "Cancel" buttons within opened modal) and you won't see any scrollbars on the page. The page is blocked. You cannot scroll it.

**Comment by andrerpena** [comment] 2016-10-01 12:53
I've noticed it too. Additionally, the fact that the parent window's width changes makes it to "shake" when you open the Modal.

**Comment by eddywashere** [comment] 2016-10-01 17:05
I think I know what's going on. Just so I have all the info, can you tell me the following: what browser, browser version and OS version are you using? Do you see any of this happen in the same portion of bootstrap docs? Thanks for reporting! I'll look into it in the meantime.

**Comment by andrerpena** [comment] 2016-10-01 17:13
![demo](http://i.imgur.com/86q4Yx9.gif)

**Comment by eddywashere** [comment] 2016-10-01 18:22
Got it. To reproduce on osx, I set `show scroll bars` to `always` in general > settings. I see the issue. In bootstrap docs, the `modal-open` class is applied to the body on open. I thought that was enough but apparently they also add padding-right to accommodate for scrollbar when present. You won't see that if your OS autohides scrollbar. I'll look into that.

The other issue in the original comment:

> The page is blocked. You cannot scroll it.

This should be the desired behavior when the modal is open. At least this is how it appears in the [bootstrap v4 modal docs](http://v4-alpha.getbootstrap.com/components/modal/) (the `modal-open` class applies `overflow:hidden` to body). 

Are you saying scrolling is blocked after it the modal is closed?

**Comment by eddywashere** [comment] 2016-10-01 22:15
@andrerpena the issue you described is fixed in `3.3.2`. @wzup I wasn't able to reproduce what you described exactly. Found something similar and opened up this issue https://github.com/reactstrap/reactstrap/issues/166. If that's what you're talking about, lets close this issue and track it over there.

**Comment by TheSharpieOne** [comment] 2017-07-25 19:00
Closing this issue as suggested above since it has not been active for several months.

**Closed by TheSharpieOne** 2017-07-25 19:00 UTC
