### ISSUE TITLE
data.filter(function(x) { return x !== null });  doesn't work in reactstrap

### ISSUE THREAD

**Issue by paullam328** [reactstrap/reactstrap#671] opened 2017-11-06 14:26 UTC
```
handleSubmitX(event) {
 var result =
            [{
                a:a
            },{filter:[null,c:c,d:d]}
           ];
        result = result.filter(function(x) { return x !== null }); 
        console.log('A bunch of queries are submitted: ' + JSON.stringify(result));

        event.preventDefault();
}
```

 Outcome before filter: A bunch of queries are submitted: [{a:a},{filter:[null,c:c,d:d]}]
 Desired outcome after filter: A bunch of queries are submitted: [{a:a},{filter:[c:c,d:d]}]

This is basically within a submit button handling function, as well as a class.

I want filter to remove the null from the array, however, in the syntax of reactstrap, it doesn't seem to work as intended.

What am I doing wrong, or else is there any special ways to do so in reactstrap?

**Comment by TheSharpieOne** [comment] 2017-11-06 14:41
This has nothing to do with reactstrap and would be a better question for stackoverflow.
A hint would be to format your code to better see the shape of the array you are defining.
You will notice none of the item in the `result` array are `null`. Add a `console.log` within the filter function callback and log `x` to see.

**Comment by TheSharpieOne** [comment] 2018-03-30 17:19
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2018-03-30 17:19 UTC
Labels: invalid, question
