### ISSUE TITLE
Reactstrap is completely unusable with Preact

### ISSUE THREAD

**Issue by dotterian** [reactstrap/reactstrap#1116] opened 2018-07-09 13:33 UTC
### Issue description

- reactstrap version `#6.2.0`
- import method `es`

### What is happening?

On first import of Reactstrap it calls `Polyfill` from `react-lifecycles-compat` on `TabContent`, even if your code doesn't use `TabContent`.
In it's turn `Polyfill` obviously fails to work with `Preact.Component` which leads to termination of rendering and whole application is now one big white screen.

### What should be happening?

Application should render normally using Preact.

### Steps to reproduce issue

1. Create project with preact, preact-compat and reactstrap
2. Try to render it

### Error message in console

```
Uncaught Error: Can only polyfill class components
    at polyfill (react-lifecycles-compat.es.js:54)
    at Object../node_modules/reactstrap/dist/reactstrap.es.js (reactstrap.es.js:5487)
```

### Code
Separate demo project showcasing this error: https://github.com/dotterian/preactstrap-error

### Possible solution
Rewrite TabContent using current React lifecycle, so there won't be any need in `react-lifecycle-compat`

### Temporary solution
Check if TabContent is React Component before applying polyfill.
```
var prototype = TabContent.prototype;

if (prototype && prototype.isReactComponent) {
  polyfill(TabContent);
}
```

**Comment by TheSharpieOne** [comment] 2018-07-09 17:45
react-lifecycle-compat was added before of #1044. It allows reactstrap to better maintain backwards compatibility with react 16.
reactstrap doesn't really try to be compatible with preact and reactstrap doesn't have any tests to ensure it works with preact. That said, we do accept PRs to improve preact compatibility as long as it doesn't hinder usage with react.

**Comment by ngyikp** [comment] 2019-10-16 00:02
Reactstrap seems to work fine on Preact X for me as long as I alias `preact/compat` mentioned in the docs: https://preactjs.com/guide/v10/switching-to-preact

**Comment by TheSharpieOne** [comment] 2019-12-10 15:46
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2019-12-10 15:46 UTC

**Comment by arleighdickerson** [comment] 2022-12-12 19:27
[`I wrote a script that can patch it in place for compatibility`](https://gist.github.com/arleighdickerson/3491aab0fb0ed54bab5e4dc3751b5300)
