### ISSUE TITLE
Tooltip gets cut off

### ISSUE THREAD

**Issue by VictorChen** [reactstrap/reactstrap#722] opened 2017-11-30 19:14 UTC
When tooltip is at the bottom of the page, it gets cut off, eg:

<img width="704" alt="screen shot 2017-11-30 at 2 12 39 pm" src="https://user-images.githubusercontent.com/1408813/33450067-a90c24ac-d5d8-11e7-99bc-761ecc114644.png">

I'd expect it to do this instead:

<img width="679" alt="screen shot 2017-11-30 at 2 13 59 pm" src="https://user-images.githubusercontent.com/1408813/33450101-bcd3b6e4-d5d8-11e7-96d3-1422f9f11443.png">

See reproducer here:

https://www.webpackbin.com/bins/-L-DH8yGOHznRTPu8TWL

**Comment by Geczy** [comment] 2017-12-13 16:26
I can't reproduce with your demo

![image](https://user-images.githubusercontent.com/1036968/33949707-6a53fdf0-dff8-11e7-9bcc-e5acbe526a6a.png)

**Comment by VictorChen** [comment] 2017-12-13 17:17
ah interesting, you might have to reduce your window's height

**Comment by TheSharpieOne** [comment] 2018-03-30 17:29
Closing as I cannot reproduce, plus I believe this issue was opened when reactstrap was using tether. reactstrap is now using Popper.js via react-popper.
Also the link above was not working for me, so here is this: https://stackblitz.com/edit/reactstrap-v5-wuqnk1?file=Example.js

**Closed by TheSharpieOne** 2018-03-30 17:29 UTC
