### ISSUE TITLE
How to put hidden per size (i.e. hidden-xs) on Col?

### ISSUE THREAD

**Issue by bherila** [reactstrap/reactstrap#482] opened 2017-06-28 18:41 UTC
I am trying to do `<Col xs={{hidden: true}}>...` but it looks like `hidden` is not supported on the `ColumnProps` 

Is there a simple way of adding this? Or should I just use className?

Thanks,
Ben

**Comment by TheSharpieOne** [comment] 2017-06-28 19:46
Since this is a utility and not restricted to just Col it is not supported by Col in that way. For now, `className` is how to achieve this.

**Comment by TheSharpieOne** [comment] 2017-08-09 19:27
I am closing this as the question has been answered and the issue is no longer active. If you are not satisfied with the answer or have further concerns on this topic, please feel free to reopen and/or comment

**Closed by TheSharpieOne** 2017-08-09 19:27 UTC
Labels: question

**Comment by klabusta** [comment] 2018-02-16 15:56
@TheSharpieOne Can you show us an example what this should look like? This won't work:

`<Row>
                        <Col xs="6" sm="4">.col-6 .col-sm-4</Col>
                        <Col xs="6" sm="4">.col-6 .col-sm-4</Col>
                        <Col className="hidden-xs" sm="4">.col .col-sm-4</Col>
                    </Row>`

**Comment by klabusta** [comment] 2018-02-16 16:16
Got it, I'm using v4 which uses something like d-*-none. See https://getbootstrap.com/docs/4.0/migration/#responsive-utilities

**Comment by reversTeam** [comment] 2019-09-26 20:46
try with **xs-hidden** not ~~hidden-xs~~

`<Col xl="2" md="2" className="text-center xs-hidden">`

**Comment by thiagomatrix** [comment] 2020-04-07 12:31
<Col xl='12' className="d-none d-xl-block" >FULL HD</Col>
<Col md='12' className="d-none d-md-block" >HD</Col>
<Col sm='6' className="d-none d-sm-block d-md-block" >SD</Col>
<Col md='4' className="d-block d-md-none" >MOBILE</Col>
