### ISSUE TITLE
How I can add animation for tooltip or popover?

### ISSUE THREAD

**Issue by romanlex** [reactstrap/reactstrap#492] opened 2017-07-07 13:01 UTC
Hello. How I can add custom CSSTransition animvation for tooltip or popever components?

**Comment by FernandoBoza** [comment] 2017-07-17 12:54
it should work like any css transition, when you hover or click on an element and change states.

**Comment by TheSharpieOne** [comment] 2018-03-30 17:17
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2018-03-30 17:17 UTC
Labels: question
