### ISSUE TITLE
Can't toggle dropdown component if there are two dropdowns bound to the same dropdown toggle function

### ISSUE THREAD

**Issue by seberik** [reactstrap/reactstrap#716] opened 2017-11-29 09:20 UTC
### Issue description

- components: `Dropdown`
- reactstrap version `4.8.0`
- import method `es`
- react version `15.4.2`
- bootstrap version `alpha 6`

### What is happening?
Can open but not close dropdown. The toggle method is triggered twice when open, likely because of document event listeners.

### What should be happening?
It should toggle the dropdowns.

### Steps to reproduce issue
1. Click to open dropdown
2. Try to close dropdown, doesn't work

### Code
https://www.webpackbin.com/bins/-L-5zU2UeXC6cKFrR3Ui

**Comment by TheSharpieOne** [comment] 2017-11-30 16:50
Working as intended. Both the of dropdowns share the same state and callbacks and thus share the fate.
It is not the intended use, but this is the intended result.

Clicking on the dropdown toggle while they are open triggers it the dropdown you did not click on to close, which calls your callback (closing all of them as that is what you callback is telling it to do) (this is done using even capture, so it happens first) then the click triggers the now closed dropdown to call your callback again (and again, this is your callback, it determines what should happen, not reactstrap) which toggles the isOpen state and thus opens the dropdown menus again.

If you need multiple dropdown, you should have multiple toggle functions (or logic within a single function to toggle the right isOpen boolean in the state) and each dropdown should have it's own isOpen boolean in the state. If you don't, then you indicate that you want the action you are seeing to happen.
If you don't want to create/manage multiple callbacks and isOpen states, you can use `UncontrolledDropdown`s which will do all of that for you.
Using `Dropdown` yourself allows you to determine and provide any logic you want for the toggle callback and isOpen prop, allowing you to create these more interesting use-cases, such as when multiple dropdown are tied together.

**Closed** 2017-12-01 12:45 UTC

**Comment by Andrew-Kang-G** [comment] 2019-09-18 06:53
The key is to add another parameter that can distinguish Dropdowns to the 'toggle' function. You can use not only two Dropdowns, but multiple ones.

```
 toggleDropdown(e, name) {

    if(name) {
      if(this.state.showDropdown[name]) {
        this.setState({showDropdown: {...this.state.showDropdown, [name]: !this.state.showDropdown[name]}})
      }else{
        this.setState({showDropdown: {...this.state.showDropdown, [name]: true}})
      }
    }

  }

this.props.groupPermissions.map((groupPermission, i) => (

            <Dropdown isOpen={showDropdown[groupPermission.name]} toggle={(e) => toggleDropdown(e, groupPermission.name)}>
                <DropdownToggle nav caret>
                    {groupPermission.name}
                </DropdownToggle>
                <DropdownMenu className="dropdown-menu-right">

                </DropdownMenu>
            </Dropdown>

        ))
```
