### ISSUE TITLE
bg="primary" is not working under <Card.Header> 

### ISSUE THREAD

**Issue by anburocky3** [reactstrap/reactstrap#1456] opened 2019-04-07 08:45 UTC
- components: `Card`
- reactstrap version `#1.0.0B6`

### What is happening?
Can't apply stylings in <Card.Header>

This is not working:
           ``` <Card.Header bg="primary">Login </Card.Header>```

But, this is working:
            ```<Card bg="primary">Login </Card>```

**Comment by TheSharpieOne** [comment] 2019-04-08 15:02
I think you have the wrong repo. It looks like you are using react-bootstrap, a traditionally bootstrap 3 react library with bootstrap 4 support in beta. This is reactstrap, a light weight bootstrap 4 react library.

In reactstrap you would do something like:

```jsx
import React from 'react';
import { Card, CardTitle } from 'reactstrap';

const Example = (props) => {
  return (
    <Card body bg="primary">
      <CardTitle>Login</CardTitle>
      ...
    </Card>
  );
};
```

You can see more examples here: http://reactstrap.github.io/components/card/

**Comment by TheSharpieOne** [comment] 2019-12-10 15:51
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2019-12-10 15:51 UTC
