### ISSUE TITLE
Modal closes on scrollbar click

### ISSUE THREAD

**Issue by makepost** [reactstrap/reactstrap#1097] opened 2018-06-26 13:19 UTC
### Issue description

- components: Modal
- reactstrap version `#6.1.0`
- import method `es`
- react version `#16.4.1`
- bootstrap version `#4.1.1`

### What is happening?

Modal appears. User tries to scroll it using wheel. It's ok. Another user tries to scroll using Chrome scrollbar. Modal closes.

### What should be happening?

Modal shouldn't close when user starts mouse press on scrollbar.

### Steps to reproduce issue

1. Open https://reactstrap.github.io/components/modals/
2. Press "Launch Modal"
3. Reduce browser window height until scroll bar appears
4. Use the scroll bar

**Comment by choncj** [comment] 2018-07-11 13:07
This is really annoying. Is there a quick fix for this?

**Comment by monteith** [comment] 2018-08-01 22:29
I'm having a hard time reproducing this with the provided instructions. Is there a trick to this I'm missing?

Chrome v67.0.3396.99

**Comment by TheSharpieOne** [comment] 2018-08-02 15:21
After doing a little digging, it appear this issue is caused by using mouse events (`mousedown` and `mouseup`) instead of the `click` event to determine when to close the modal. It uses the mouse events to address #1046 via #1047.

Click events don't seem to be trigged by clicking the scroll bar but mouse event are... and the event doesn't really indicate that it was the scrollbar that was click.

I would imagine there is a way to keep using mouse events but some how determine that the mouse event was the scrollbar that was clicked... but if that is not possible, we might need to remove #1047 as bootstrap has the same problem that #1047 fixes and bootstrap doesn't have this problem.

**Comment by makepost** [comment] 2018-08-06 14:08
Thanks for investigation. Depending on the OS and desktop environment, scrollbar can appear over the window on demand, not altering the viewport dimensions. So it'd be unrealiable to use a commonly suggested workaround, comparing mouse coordinate and window width. Because of that, I suggest the combination of `mouseDown`, to keep the fix of the text selection issue you mentioned, and `click`, which isn't fired on scrollbar usage. Made a pull request, please test for yourself and review.

**Closed** 2018-08-06 14:30 UTC
Labels: BS compatibility, PR Welcome, bug, help wanted
