### ISSUE TITLE
Upgrade Bootstrap 4 from Alpha 6 to Beta

### ISSUE THREAD

**Issue by benxgao** [reactstrap/reactstrap#546] opened 2017-08-16 09:12 UTC

**Comment by GitShaffi** [comment] 2017-08-16 09:21
DropDown in reactstrap is broken after upgrading from alpha 6 to Beta. Please make reactstrap compatible with latest version of BootStrap4.

**Comment by KeitIG** [comment] 2017-08-16 11:46
Yes please :) The beta being out, it should be far more stable now and there should not be new breaking changes once reactstrap will be ready for the beta.

**Comment by KeitIG** [comment] 2017-08-16 11:53
Dupe with https://github.com/reactstrap/reactstrap/issues/487 btw

**Comment by TheSharpieOne** [comment] 2017-08-16 15:38
Duplicate of #487.
Closing this in favor of #487. Please use #487 to track this issue.

**Closed by TheSharpieOne** 2017-08-16 15:38 UTC
