### ISSUE TITLE
React can't run after installing reactstrap

### ISSUE THREAD

**Issue by Guykondas** [reactstrap/reactstrap#913] opened 2018-03-19 13:55 UTC
### Issue description
'''
I setup my and it was runing and i npm install reactstrap and it's not working anymore.
Please any help
## Error message in console

```
$ react-scripts start
sh: 1: react-scripts: not found
error An unexpected error occurred: "Command failed.
Exit code: 127
Command: sh
Arguments: -c react-scripts start
Directory: /home/lamar/react-today/my-app-today
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/lamar/react-today/my-app-today/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by TheSharpieOne** [comment] 2018-03-19 17:02
Duplicate of #888
try using `npm start`, or installing create-react-app globally, or file an issue with create-react-app since they make the `react-scripts` which are not found on your local machine.

**Closed by TheSharpieOne** 2018-03-19 17:02 UTC

**Comment by Guykondas** [comment] 2018-03-20 10:47
Okay.  thanks.
It was working fine till install the reactstrap

**Comment by TheSharpieOne** [comment] 2018-03-20 12:20
Reactstrap doesn't do anything with your local bash instance or your executable path (where react-scripts would need to be in order for you to type "react-scripts start" and your computer to find it react-scripts).
Since it is saying it's not found, it's either not installed or not in your path.
Reactstrap doesn't document using react-scripts (reactstrap uses it internally with npm/yarn test, but that calls the one in node modules and with the test command), so the issue is with the project which told you to use that. I'm guessing create react app is where you found the instructions, this may be a legitimate issue for them (maybe, untested theory): when installing another module which depends on react-scripts, the root project's commands cannot find react-scripts.
