### ISSUE TITLE
How to use <input /> as readonly

### ISSUE THREAD

**Issue by sovanjana** [reactstrap/reactstrap#543] opened 2017-08-14 19:12 UTC
I want to use an `<input />` as **readonly** but in **reactstrap** no such props available for `<Input />` . Can anyone help me to use `<input />` as **readonly**.

**Comment by TheSharpieOne** [comment] 2017-08-14 20:36
all props not used/consumed by reactstrap will be passed down and in the case of reactstrap's `Input` they are passed down to the raw `<input>`. React uses the API names instead of the common HTML names (e.g. `className` vs `class`) and in the case of `readonly` it is `readOnly` in react. So, `<Input readOnly />` is what you are looking for.

Refernces:
https://facebook.github.io/react/docs/dom-elements.html#all-supported-html-attributes
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

**Comment by TheSharpieOne** [comment] 2017-09-15 22:36
@sovanjana does the above answer your question?

**Comment by ejdelmonico** [comment] 2017-09-20 21:55
If no `onChange` attached to the input in React, it is readonly by default I thought.

**Comment by TheSharpieOne** [comment] 2017-09-20 23:06
@ejdelmonico not really. What you mention is the difference between controlled and uncontrolled components/inputs. Uncontrolled components (which you do not specfic a `value` props, `defaultValue` allow one to set a default value) work differently / more natively. Controlled components require the `value` prop (which cannot be `undefined`) and every time the user changes the value a render occurs and sets the value to what is in the value prop. If you do not have an `onChange` to track the value the user is entering, it effectively not change the value and appear to be readonly. Note: that with controlled components, when the user enter's a value it **does** update the input's value, but is quickly changed back to the value of the `value` prop when it renders again. This is why the `event.target.value` is the updated value.

https://www.webpackbin.com/bins/-KuWVXEm4R1mdgJZD00N

**Comment by ejdelmonico** [comment] 2017-09-21 15:02
@TheSharpieOne Thank you for the thorough explanation and example to improve my understanding.

**Comment by shkfnly** [comment] 2017-10-03 08:35
@sovanjana  use the plaintext tag on the <Input /> function

**Comment by TheSharpieOne** [comment] 2018-03-30 17:05
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2018-03-30 17:05 UTC
Labels: question

**Comment by nvisium-peter-eldritch** [comment] 2020-04-19 14:16
In React.JS, if you are using JSX, then readOnly functions in a component as a boolean property.

Below is a styled component (See [Styled-Components](https://styled-components.com/))

```
const StyledInputField = styled.input`
    width: ${props.width ? props.width : '100%'};
    height: ${props.height ? props.height : '42px'};
    padding: 10px 10px 10px 10px';
    font-family: Montserrat, sans-serif;
    font-size: 16;
    font-weight: 600;
    text-align: left;
`

```

You do not really have to know or understand Styled Components to understand this answer. Now suppose I want to set the readOnly attribute on a component that I create from my `StyledInputField` component declaration?

```
<StyledInputField type="text" readOnly={true} />
```

React.JS interprets ReadOnly as the ReadOnly attribute and interprets its having a truthy value as the given component should be rendered with the readOnly attribute set on it.

This will in effect give you the following:

CSS:
```
.styledInputField {
    width: ${props.width ? props.width : '100%'};
    height: ${props.height ? props.height : '42px'};
    padding: 10px 10px 10px 10px';
    font-family: Montserrat, sans-serif;
    font-size: 16;
    font-weight: 600;
    text-align: left;
}
```

HTML:
```
<input type="text" class="styledInputField" readOnly />
```

React.JS recognizes the readOnly property and handles it appropriately.  One may also use a state value or a `prop`

Example - here I am using props.isReadOnly to set the readOnly attribute on StyledInputField:

```
<StyledInputField type="text" readOnly={props.isReadOnly} />
```

If `props.isReadOnly` is truthy, then the readOnly property will be set. If `props.isReadOnly` is falsy, it will not be set.

* [True and False vs. "Truthy" and "Falsey" (or "Falsy") in Ruby, Python, and JavaScript](https://gist.github.com/jfarmer/2647362)
* [How to Set the readOnly TextBox in React.JS TextBox component
](https://ej2.syncfusion.com/react/documentation/textbox/how-to/set-the-read-only-textbox/)
