### ISSUE TITLE
Cannot read property 'jquery' of undefined in Popper

### ISSUE THREAD

**Issue by GitShaffi** [reactstrap/reactstrap#642] opened 2017-10-19 09:50 UTC
### Issue description

- components: `Dropdown`
- reactstrap version `#5.0.0-alpha.3`
- react version `#15.6.1`
- bootstrap version `#4.0.0-beta`

### What is happening?

An error is thrown when opening Dropdown component

### Error message in console
```
Uncaught TypeError: Cannot read property 'jquery' of undefined
    at new Popper (popper.js?660c:2319)
    at Popper._createPopper (Popper.js?1a33:173)
    at Popper._updatePopper (Popper.js?1a33:152)
    at Popper.componentDidMount (Popper.js?1a33:129)
    at eval (ReactCompositeComponent.js?063f:262)
    at measureLifeCyclePerf (ReactCompositeComponent.js?063f:73)
    at eval (ReactCompositeComponent.js?063f:261)
    at CallbackQueue.notifyAll (CallbackQueue.js?7abf:74)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js?2d36:78)
    at ReactReconcileTransaction.closeAll (Transaction.js?91bc:207)
```

### What should be happening?

Dropdown should open

**Comment by TheSharpieOne** [comment] 2017-10-19 13:24
You have to use DropdownToggler

**Comment by NullVoxPopuli** [comment] 2017-10-23 15:54
this also causes the error: 
```js
// /src/ui/components/reactstrap/dropdown.jsx
import styled from 'styled-components';

import { DropdownToggle } from 'reactstrap';

export const StylelessDropdownToggle = styled(DropdownToggle)`
  border: none !important;
  background: none !important;
  border-radius: unset;
  padding: 0;
  margin: 0;
`;
```
and then using that in place of the original DropdownToggle doesn't work. (I just want a toggle that doesn't look like a button)

**Comment by TheSharpieOne** [comment] 2017-10-23 16:41
When anything within the `DropdownToggle` is clicked, the event will bubble and to the `DropdownToggle` (as long as you don't explicitly stop propagation) and thus trigger the toggle callback. Adding `onClick` to an component within `DropdownToggle` means that the `onClick` as well as the toggle callback will be called. If the `onClick` calls the toggle callback itself, then the toggle callback will be called twice.

**Comment by NullVoxPopuli** [comment] 2017-10-23 16:56
jsx desperately needs a yield syntax. :-(

it'd be much more straight forward to have:

```jsx
<DropdownMenu as |menu, toggler, isOpen|>
  <menu.Toggler toggle={toggler} />

   { isOpen ? 'Open' : 'Closed' }
</DropdownMenu>
```

**Comment by TheSharpieOne** [comment] 2017-11-16 04:42
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2017-11-16 04:42 UTC
