### ISSUE TITLE
Combining Pagination with react-router-dom Link

### ISSUE THREAD

**Issue by sjorsvanheuveln** [reactstrap/reactstrap#566] opened 2017-09-08 17:25 UTC
Is there a way of using pagination with the Link tag/component from the react-router-dom library. I cannot insert it into the pagination example as it give errors for putting an <a> tag inside an <a> tag. Is there a workaround?

**Comment by ananthamapod** [comment] 2017-09-14 12:26
https://github.com/reactstrap/reactstrap/issues/83#issue-168537815

https://github.com/reactstrap/reactstrap/issues/298

**Comment by cairocoder** [comment] 2017-09-28 03:35
@ananthamapod Thanks for the note, you saved my life 👍

**Comment by TheSharpieOne** [comment] 2017-11-16 04:54
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2017-11-16 04:54 UTC
