### ISSUE TITLE
Only using Reactstrap to replace Bootstrap 4's Jquery-based components

### ISSUE THREAD

**Issue by domi91c** [reactstrap/reactstrap#656] opened 2017-10-25 23:59 UTC
To make it easier (or at least more familiar) to style an app, I was thinking of only using Reactstrap for the parts of Bootstrap that require Jquery, and using regular Bootstrap markup for the rest of the app. For example, 

        <nav class="navbar navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <ul className="navbar-nav ml-auto">
            <NavDropdown isOpen={this.state.dropdownOpen} toggle={this.toggle}>
              <DropdownToggle nav caret>
                Dropdown
              </DropdownToggle>
              <DropdownMenu right>
                <DropdownItem header>Header</DropdownItem>
                <DropdownItem disabled>Action</DropdownItem>
                <DropdownItem>Another Action</DropdownItem>
                <DropdownItem divider/>
                <DropdownItem>Another Action</DropdownItem>
              </DropdownMenu>
            </NavDropdown>
          </ul>
        </nav>

Does it make sense to do so, or should I be using ReactStrap for everything?

**Comment by TheSharpieOne** [comment] 2017-10-26 01:36
To me it makes sense to use all of reactstrap for a few reasons.

1. No need to have className everywhere. This makes your jsx a little clearer and nicer to look at. You already have a mixture of class and className in the example you made. 
2. Reactstrap abstracts underlying changes to bootstrap (as much as possible). When bootstrap changes, reactstrap will adapt but the way you use reactstrap will remain unchanged. Note this is less likely since bootstrap v4 is coming stable, but before when classNames for things like button outlines changed, users of reactstrap didn't have to update their jsx.
3. It's consistent and ensures the bootstrap classes and extra attributes are correct (much harder to typo, especially with typescript definitions)

There are some potential downside.
1. Your not using bootstrap directly so you might not learn/know the underlying classNames and such being used (mostly a problem for when you change to a project not using reactstrap)
2. If you do already know bootstrap (v4), you'll have to learn reactstrap. It's not hard, we try to make component names and props predictable.
3. You might have to take a given markup and convert it to reactstrap.

**Comment by TheSharpieOne** [comment] 2017-11-21 10:39
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2017-11-21 10:39 UTC
Labels: question
