### ISSUE TITLE
Sidebar menu

### ISSUE THREAD

**Issue by santanapaulo** [reactstrap/reactstrap#1544] opened 2019-06-21 18:22 UTC
Is there any easy way to implement a Sidebar menu using reactstrap?

I was wondering if we can use the Navbar component to do that, but I am not sure about it.

**Comment by TheSharpieOne** [comment] 2019-06-21 18:39
While it's a little old and some of the things have changed a little, you should be able to use #544 and just migrate the component usage.

**Comment by TheSharpieOne** [comment] 2019-12-10 15:49
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2019-12-10 15:49 UTC
