### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by jdpagley** [reactstrap/reactstrap#909] opened 2018-03-16 14:51 UTC
### Issue description

- components: `unknown`
- reactstrap version `5.0.0-beta.2`
- import method `es6/babel/webpack`
- react version `15.6.2`
- bootstrap version `4.0.0`

### What is happening?

When I npm installed v5.0.0-beta.2 it began giving be the error in my console below after bundling my code and refreshing my browser. I reverted back to the v5.0.0-beta and the error went away. Something inside of of beta-2 is causing the error I'm guessing.

### Error message in console

![image](https://user-images.githubusercontent.com/4016177/37526881-f29ac476-2906-11e8-9ff1-8c816f61c425.png)
When I click on the bundled file it takes me to this line. It appears to be a reactstrap file:
![image](https://user-images.githubusercontent.com/4016177/37526953-2ffa6880-2907-11e8-9073-d05827f408a0.png)

**Comment by artyomlagun** [comment] 2018-03-16 15:17
I have the same issue

**Comment by TheSharpieOne** [comment] 2018-03-16 15:54
Duplicate of #870
Duplicate of #872

**Closed by TheSharpieOne** 2018-03-16 15:54 UTC
