### ISSUE TITLE
Modal with Legacy context api and findDOMNode warnings on console when open

### ISSUE THREAD

**Issue by hermeshcg** [reactstrap/reactstrap#2065] opened 2021-01-04 17:29 UTC
- components: `Modal`
- reactstrap version `"^8.7.1"`
- import method `umd/csj/es` 
- react version `^17.0.1`
- bootstrap version `^4.5.3`

### What is happening?

I'm using modal by reactstrap in a project, when this modal is open it appears a few warnings in the console

### What should be happening?

Not showing warnings i guess

### Steps to reproduce issue

1. Open console
2. Open an reactstrap modal

### Error message in console

Error 1
```
index.js:1 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Transition
```

Error 2

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference.
```

**Comment by kyletsang** [comment] 2021-01-04 18:18
Dupe of #1833

**Closed by kyletsang** 2021-01-04 18:18 UTC
Labels: duplicate
