### ISSUE TITLE
Nested modals shift+tab focuses items of the underlying modal

### ISSUE THREAD

**Issue by krnlde** [reactstrap/reactstrap#1497] opened 2019-05-21 09:03 UTC
- components: `modal`
- reactstrap version `#8.0.0`
- import method `es`
- react version `#16.8.6`
- bootstrap version `#4.3.1`

### What is happening?

As seen in the [Nested Modals](https://reactstrap.github.io/components/modals/) example of the documentation, if you open the nested modal `tab` into the focusable items ("Done" and "All Done") and then `shift+tab` back items of the previous modal are focused.

### What should be happening?

When pressing `shift+tab` the previously focused item should be focused.

### Steps to reproduce issue

1. Go to the [Modals](https://reactstrap.github.io/components/modals/) page
2. Find the "Nested Modals" example
3. Open the example modal
4. Open its nested modal
5. Press `tab` twice to focus the "All Done" button
6. Press `shift+tab` to focus the "Done" button
7. The "Cancel" button of the underlying modal will be focused

**Comment by watinha** [comment] 2020-07-19 15:36
Duplicate of #1679?

**Comment by krnlde** [comment] 2020-07-28 11:02
Yes it is. But... but I was first :D

**Closed** 2020-12-23 19:26 UTC
