### ISSUE TITLE
No animation on modal mounting

### ISSUE THREAD

**Issue by Rootmafia** [reactstrap/reactstrap#607] opened 2017-10-02 22:48 UTC
**## Issue description**

- version "reactstrap": "next",
- components: Modal
- react version "^16.0.0",

There is no fade in animation on Modal appearing, have you removed  it?

**Comment by virgofx** [comment] 2017-10-02 22:58
This is a valid bug we need to investigate further.

**Comment by devonJS** [comment] 2017-10-03 07:30
@virgofx hello! could i take a stab at this one? been wanting to contribute for a while, would investigate tomorrow after work!

**Comment by TheSharpieOne** [comment] 2017-10-03 12:09
@devonJS go for it. There is a branch which updates the dev version of react in this project to 16. You'll probably need to branch off of that or something to see the issue since this only happens with react 16.

**Comment by virgofx** [comment] 2017-10-03 13:19
I believe the issue is we need to force a repaint on the initial load once it applies the first class. It looks like CSSTransition has this built in; however, we opted to use Transition, so it may behoove us to switchover; however, we need to update this everywhere and ensure we use the bootstrap version of the classes (e.g. `show`).

**Comment by TheSharpieOne** [comment] 2017-10-03 13:42
There is an issue which was recently open with react-transition-group: https://github.com/reactjs/react-transition-group/issues/216. Not sure if it is valid or not, but it seems similar to what we are experiencing and thus we may be able to benefit from the solution to it; regardless of whether it is an issue with react-transition-group or not

**Comment by devonJS** [comment] 2017-10-03 17:17
@virgofx @TheSharpieOne Great, thanks for the direction on this issue. Will consider what you both mentioned above when approaching this!

**Comment by devonJS** [comment] 2017-10-05 09:08
hmmm there seems to be a couple of things to consider for React 16:

1.  As mentioned, react-transition-group seems to not work as intended
2. Seems ReactDOM.createPortal would be the preferred way to accomplish what ReactDOM.unstable_renderSubtreeIntoContainer does [react/issues/10309](https://github.com/facebook/react/issues/10309#issuecomment-318431005), documentation of what it does seems this way as well

ReactDOM.createPortal is such a big feature in React 16 that for this to play with React 16 and its future versions it should be used, what do you think? It also seems lik

**Comment by TheSharpieOne** [comment] 2017-10-05 11:03
#601 has the task of upgrading to portals, but to better maintain compatibility with < react 16 the suggestion is to use `createPortal` and fallback to `unstable_renderSubtreeIntoContainer` if it is not there. material did [something similar](https://github.com/callemall/material-ui/pull/7218/commits/1d3c5c1719cc78144d9a2fbf21d60857e1c11ae4)
As for `Transition` vs `CSSTransition` Yes, we are using react-transition group, The doc you reference are old, it itself references react-transition-group v1. The v2 docs can be found [here](https://reactcommunity.org/react-transition-group/). I think the preference is for everything to use `Transition` to be consistent. Plus, I am not too sure if bootstrap has the [classes](https://github.com/twbs/bootstrap/blob/7b766e1ad53b0c22de42dac04d2472f287334e2a/scss/_transitions.scss) to support the [class convention](https://reactcommunity.org/react-transition-group/#CSSTransition-prop-classNames).

**Comment by devonJS** [comment] 2017-10-11 09:08
@TheSharpieOne sent PR, I'll leave the `createPortal` and `unstable_renderSubtreeIntoContainer` fallback to who ever picks up #601

**Comment by jonathanazulay** [comment] 2017-10-16 12:18
I was gonna file this issue and reproduced it here. Also reproduces #360 

[https://codesandbox.io/embed/8x3nm1l659](https://codesandbox.io/embed/8x3nm1l659)

**Comment by chrisparton1991** [comment] 2017-10-19 11:19
To clarify, by having no animation on modal mounting are you saying that the modal instantly appears, or that it remains invisible?

I'm experiencing an issue where my modal has a `fade` class attached that never gets removed, leaving it invisible. If that's the issue here, I won't raise a dupe.

**Comment by TheSharpieOne** [comment] 2017-10-19 14:03
The fade class stays the entire time the modal exists. This is how bootstrap does it. An additional class is added to affect the opacity.

**Comment by Kielan** [comment] 2018-01-01 14:29
@TheSharpieOne Any update on this? I see the commit referencing this issue 2 months ago is just one line long. I have set up modals a few times in react and want to give it a go but I see two separate pr's, one which is not merged.

**Comment by jonathanazulay** [comment] 2018-01-01 15:56
@Kielan Seems to be fixed in v5.0.0-alpha4, it appears to be a fade in and out on my iPhone

**Comment by virgofx** [comment] 2018-01-01 20:52
I also believe this is fixed. There may be a few weird cases with large timeouts, but all of my use cases seem fixed.

**Comment by bonniejools** [comment] 2018-01-03 17:38
I can confirm that is fixed for me.

**Comment by TheSharpieOne** [comment] 2018-03-30 17:19
Fixed in v5, closing.

**Closed by TheSharpieOne** 2018-03-30 17:19 UTC
Labels: Hacktoberfest, bug, in-progress
