### ISSUE TITLE
Tooltip crash the current open tab in the browser when the space is not availaible for the tooltip;

### ISSUE THREAD

**Issue by Aashishgtbit** [reactstrap/reactstrap#1664] opened 2019-10-15 08:18 UTC
- components: `Tooltip`
- reactstrap version `#8.0.1`
- import method `umd/csj/es` 
- react version `#16.9.0`
- bootstrap version `#4.x`

### What is happening?

When I use the tool tip in my web app if the browser has not enough space for the tooltip then it will crash the current open tab . For example I have a side bar which has some data rows and I want to use tooltip for each item and position it right  , It is working perfectly fine for the top position .
### What should be happening?

it should adjust its position automatically when enough space is not available .
### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by nylon22** [comment] 2019-10-17 18:50
Looks like duplicate of #1488 and #1482

**Closed** 2019-10-18 03:41 UTC
