### ISSUE TITLE
Modal Error: Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by Heizyuan** [reactstrap/reactstrap#659] opened 2017-10-26 18:24 UTC
### Issue description

- components: `Modal`
- reactstrap version `#4.8.0`
- import method `es`
- react version `#16.0.0`
- bootstrap version `#4.0.0-beta.2`

### What is happening?

I encountered the 'Uncaught TypeError: Cannot read property 'parentNode' of undefined' error when trying the Modal examples. What should I do to solve this problem? Thank you in advance.

### Error message in console

Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at Modal.renderIntoSubtree (webpack-internal:///./node_modules/reactstrap/dist/reactstrap.es.js:2518)
    at Modal.show (webpack-internal:///./node_modules/reactstrap/dist/reactstrap.es.js:2484)
    at Modal.togglePortal (webpack-internal:///./node_modules/reactstrap/dist/reactstrap.es.js:2438)
    at Modal.componentDidUpdate (webpack-internal:///./node_modules/reactstrap/dist/reactstrap.es.js:2378)
    at commitLifeCycles (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11517)
    at commitAllLifeCycles (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12294)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:1338)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:1195)
    at commitAllWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12415)

### Code
The code I was running is:
https://reactstrap.github.io/components/modals/

**Comment by A-Tokyo** [comment] 2017-10-26 19:39
@Heizyuan bump your version number to: `^5.0.0-alpha.3` it worked for me.


Although I also had to upgrade these since I used them:
```
 "react-addons-css-transition-group": "^16.0.0-alpha.3",
 "react-addons-transition-group": "^16.0.0-alpha.3",
```

**Comment by TheSharpieOne** [comment] 2017-10-26 21:02
Yes, this is an issue with portals in react 16. They do not return the reference needed for focus. You can disable the autoFocus by passing `autoFocus={false}` to the `Modal`, but it is best to just upgrade to 5.0.0-alpha.3 as A-Tokyo mentioned.

The upgrade is also recommended since you are using bootstrap 4.0.0-beta.2, the 4.8.0 version you are on only supports 4.0.0-alpha.6. Plus, 4.8.0's react peerDep does not allow react 16, so you are probably getting warning.

**Comment by Heizyuan** [comment] 2017-10-27 03:49
Problems solved as well as Alert errors. Thank you all.

**Comment by German91** [comment] 2017-10-27 11:46
I did what A-Tokyo said and It works perfectly now. Thank you very much.

**Comment by thangchung** [comment] 2017-11-01 04:44
@TheSharpieOne It works when I did like you said. But I think we need to wait a while for all libs are going to stable with React 16.x. Anw, thank you 👍

**Comment by TheSharpieOne** [comment] 2017-11-16 04:50
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2017-11-16 04:50 UTC
