### ISSUE TITLE
Navbar default collapse

### ISSUE THREAD

**Issue by osa10928** [reactstrap/reactstrap#564] opened 2017-09-05 00:35 UTC
Hello, I'm new to reactstrap and have a question I can't find the answer to anywhere. I want to make a navbar similar to the one in the example [here](https://gist.github.com/eddywashere/e13033c0e655ab7cda995f8bc77ce40d) but I want the navbar to be collapsed by default (regardless of screen size). How do I do that?

**Comment by HendrikJanssen** [comment] 2017-09-05 18:54
As you can see in 
`this.state = {
      isOpen: false
    };`
the navbar is already collapsed by default. I had a similar problem (navbar was open by default) when i used the bootstrap 4 **beta** instead of the **alpha**. 
Reactstrap is currently not compatible with the bootstrap beta so you have to use the alpha build until they update it to support the beta.

**Comment by osa10928** [comment] 2017-09-05 19:10
Thanks for answering. I am using bootstrap 4 alpha but I'm still experiencing the problem. I notice the documentation says to import import 'bootstrap/dist/css/bootstrap.css'; to my src/index.js file. I'm a little confused on what my scr/index.js file is since I'm using webpack and exporting the bundle to an internal directory which has it's own sass file (which currently includes bootstrap 4 alpha  as a mixin). Should I still import the bootstrap file to my root react component (or somewhere else) or is my set up correct?

**Comment by TheSharpieOne** [comment] 2017-09-05 19:19
Can you post the code that you have? I think the issue may be that you are missing the the `toggleable` prop.

**Comment by osa10928** [comment] 2017-09-05 19:28
import React from 'react';
    import githubIcon from '../../src/assets/images/social-media-icons/Github.svg';
    import linkedinIcon from '../../src/assets/images/social-media-icons/Linkedin.svg';
    import twitterIcon from '../../src/assets/images/social-media-icons/Twitter.svg';
    import facebookIcon from '../../src/assets/images/social-media-icons/Facebook.svg';
    import instagramIcon from '../../src/assets/images/social-media-icons/Instagram.svg';
    import {
      Collapse,
      Navbar,
      NavbarToggler,
      NavbarBrand,
      Nav,
      NavItem,
      NavLink,
      Container,
      Row,
      Col,
      Jumbotron,
      Button
    } from 'reactstrap';
    
    class MyNav extends React.Component {
      constructor(props) {
        super(props);
    
        this.toggle = this.toggle.bind(this);
        this.state = {
          isOpen: false
        };
      }
      toggle() {
        var toggleButton = document.getElementById('navtoggle');
        var brand = document.getElementById('navbrand')
        this.setState({
          isOpen: !this.state.isOpen
        });
        if (!this.state.isOpen) {
          toggleButton.classList.remove("collapsed");
          brand.classList.add("self-center");
        } else {
          toggleButton.classList.add("collapsed");
          brand.classList.remove("self-center");
        }
      }
    
    	render() {
    		return (
    			<Navbar className="fixed-top" color="inverse" inverse toggleable>
              <button id="navtoggle" className="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" onClick={this.toggle}>
                  <span></span>
                  <span></span>
                  <span></span>
              </button>
              <NavbarBrand id="navbrand" href="https://osa10928.github">Stephen Agwu</NavbarBrand>
              <Collapse isOpen={this.state.isOpen} navbar>
                <Nav navbar className="text-center">
                  <NavItem>
                    <NavLink href="https://osa10928.github.io/about">About</NavLink>
                  </NavItem>
                  <NavItem>
                    <NavLink href="https://osa10928.github.io/portfolio">Portfolio</NavLink>
                  </NavItem>
                  <NavItem>
                    <div id="social-media" className="conatainer-fluid">
                    <div className="d-flex flex-nowrap justify-content-center">
                      <div className="icon-container col">
                        <a href="https://github.com/osa10928" target="_blank">
                          <img src={githubIcon} alt="Github icon" title="Gitgub" className="img-fluid" />
                        </a>
                      </div>
                      <div className="icon-container col">
                        <a href="https://www.linkedin.com/in/stephen-agwu/" target="_blank">
                          <img src={linkedinIcon} alt="Linkedin icon" title="Linkedin" className="img-fluid" />
                        </a>
                      </div>
                      <div className="icon-container col">
                        <a href="https://twitter.com/King_DREAMER" target="_blank">
                          <img src={twitterIcon} alt="Twitter icon" title="Twitter" className="img-fluid" />
                        </a>
                      </div>
                      <div className="icon-container col">
                        <a href="https://www.facebook.com/stephen.agwu" target="_blank">
                          <img src={facebookIcon} alt="Facebook icon" title="Facebook" className="img-fluid" />
                        </a>
                      </div>
                      <div className="icon-container col">
                        <a href="https://www.instagram.com/osa10928/" target="_blank">
                          <img src={instagramIcon} alt="Instagram icon" title="Instagram" className="img-fluid" />
                        </a>
                      </div>
                    </div>
                    </div>
                  </NavItem>
                </Nav>
              </Collapse>
            </Navbar>
    		)
    	}
    }
    
    export default MyNav;


I have elected not to use the <NavbarToggler> component, in favor of a custom made icon/button, but I've copied and pasted the exampe navbar from the like I stated in the original quesiton and I get the same problem  with the navbar not being collapsed at screen sizes larger than 575px (I can actually see a media query taking effect in chromes devtools).

**Comment by lirenyeo** [comment] 2017-09-08 08:01
Every time you `setState` for `isOpen`, `render()` is called.
Remove all the DOM manipulations in your `toggle()` function.

Then do something like this for your `navtoggle` and `navbrand`:
```
<button
  id="navtoggle"
  className={ `navbar-toggler navbar-toggler-right ${ this.state.isOpen ? "collapsed" : ""}` }
  ...
```
That's the whole point of using React.

**Comment by TheSharpieOne** [comment] 2018-03-30 17:16
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2018-03-30 17:16 UTC
