### ISSUE TITLE
How to increase Modal width or change color

### ISSUE THREAD

**Issue by arpitprod** [reactstrap/reactstrap#672] opened 2017-11-07 11:35 UTC
### i need to change Modal width to '650px'

- components: `Modal`
- reactstrap version `#5.0.0-alpha.3`
- react version `#16.0.0`
- bootstrap version `#4.0.0-beta.2`

### What is happening?

I added my inline style in Modal or ModalBody
    `style={{width:'600px'}}`
or
`style={{background-color:transparent}}`
but this is not working. then I checked in browser, div tag with .modal-content css class is middle in Modal and ModalBody. 
so, where should I write this css style and className

**Comment by gergely-nagy** [comment] 2017-11-07 13:22
Duplicate of #595

**Comment by TheSharpieOne** [comment] 2017-11-07 13:47
We have only been creating special props to apply classes to various elements within the more complex components. `Modal` allows you to add a class to pretty much any of the elements it generates. Through the class, you can apply various styles.
This is from the docs: 
>  className: PropTypes.string,
>  wrapClassName: PropTypes.string,
>  modalClassName: PropTypes.string,
>  backdropClassName: PropTypes.string,
>  contentClassName: PropTypes.string,

In #595, it is mentioned how to use other props (such as `size`) to create custom classes, matching bootstraps class convention and thus allowing you to extend the bootstrap framework.

**Comment by arpitprod** [comment] 2017-11-08 06:46
ok, sorry for duplicate question
we can change size of modal with add props size="lg"

now How to change color of modal
I added props
`contentClassName={modalContent}`
and modalContent is a object 
`
const modalContent = {
  backgroundColor: 'transparent'
}
`
but contentClassName should be string
then how to use this
Please give a example

**Comment by gergely-nagy** [comment] 2017-11-08 08:31
You do not have to overwrite the '.modal-content' class.
When you add the ```contentClassName="bg-light"``` prop, you will get:

```html
<div class="modal-content bg-light>
...content
</div>
```

you just need to add the ```bg-light``` class to your custom css file.

Demo: https://www.webpackbin.com/bins/-KyPdCLBEfrxygiRVaB3

**Comment by arpitprod** [comment] 2017-11-08 11:40
yes, it's working but i want background color transparent
so, how to use transparent color

**Comment by TheSharpieOne** [comment] 2017-11-08 12:55
You can create a new class (something like `bg-transparent`) and add it to your stylesheet. Then add that class to contentClassName.

**Comment by JeffWScott** [comment] 2017-11-08 16:39
How do I make it larger than the "lg" size.  the lg size is still quite small.

**Comment by TheSharpieOne** [comment] 2017-11-08 19:30
bootstrap only has "sm" and "lg", but you can can use `size="xl"` if you add `.modal-xl` to your custom stylesheet and give it a value.
See https://github.com/reactstrap/reactstrap/issues/595#issuecomment-332658152

**Comment by TheSharpieOne** [comment] 2017-11-21 10:34
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2017-11-21 10:34 UTC

**Comment by AustrisC** [comment] 2018-03-07 15:28
Is it possible to owerride 
`@media (min-width: 576px) {
    .modal-dialog {
      max-width: 500px;
    }
  }`
in order to set `max-width` to a higher value?

**Comment by DumiduM** [comment] 2020-05-29 07:30
> You do not have to overwrite the '.modal-content' class.
> When you add the `contentClassName="bg-light"` prop, you will get:
> 
> ```
> <div class="modal-content bg-light>
> ...content
> </div>
> ```
> 
> you just need to add the `bg-light` class to your custom css file.
> 
> Demo: https://www.webpackbin.com/bins/-KyPdCLBEfrxygiRVaB3

Hi, can you explain furthermore, the Demo link seems broken
