### ISSUE TITLE
DropdownItem Links in Firefox not working

### ISSUE THREAD

**Issue by arisAlexis** [reactstrap/reactstrap#1245] opened 2018-10-03 10:38 UTC
- components: `NavLink`, `DropdownItem`
- reactstrap version `#6.3.0`
- import method `es` 
- react version `#16.4.1`
- bootstrap version `#4.1.1`

### What is happening?

The NavLink that is inside a DropdownItem inside a DropdownMenu is working fine in Chrome but not in Firefox (old and newest versions).

### What should be happening?

Following the link

### Steps to reproduce issue

Click on link

### Error message in console

None

```
<UncontrolledDropdown nav inNavbar>
                  <DropdownToggle nav caret>
                    Help
                  </DropdownToggle>
                  <DropdownMenu right>
                    <DropdownItem>
                      <a href="/faq">FAQ</a>
                    </DropdownItem>
                    <DropdownItem>
                      <NavLink href="/documentation">Documentation</NavLink>
                    </DropdownItem>
                    <DropdownItem>
                      <Link to="/howitworks">How It Works</Link>
                    </DropdownItem>
                  </DropdownMenu>
                </UncontrolledDropdown>
```

Note that neither of the three methods are working in Firefox and all methods are working in Chrome

**Comment by TheSharpieOne** [comment] 2018-10-03 21:20
Duplicate of #1143

Put the `href` on the `DropdownItem` for standard links. Use `tag={Link}` on `DropdownItem` to use react-router-dom's `Link` (and put the `to` on their as well).

Check out #1143 and #54

**Closed by TheSharpieOne** 2018-10-03 21:20 UTC
