### ISSUE TITLE
Pass className prop in the end of class list

### ISSUE THREAD

**Issue by finom** [reactstrap/reactstrap#915] opened 2018-03-19 19:43 UTC
### Issue description

All components (at least ones I've checked) pass `className` as first class name to `classNames` function like that:

```
const classes = mapToCssModules(classNames(
      className, // <---
      'btn',
      `btn${outline ? '-outline' : ''}-${color}`,
      size ? `btn-${size}` : false,
      block ? 'btn-block' : false,
      { active, disabled: this.props.disabled }
    ), cssModule);
```

### What is happening?

This requires me to use `!important` if I try to override CSS of built-in class.

### What should be happening?

Passed `className` should be the last class name for class list to make possible to override default CSS without use of `!important`.

```
const classes = mapToCssModules(classNames(
      'btn',
      `btn${outline ? '-outline' : ''}-${color}`,
      size ? `btn-${size}` : false,
      block ? 'btn-block' : false,
      { active, disabled: this.props.disabled },
      className // <---
    ), cssModule);
```

Thank you for the library!

**Comment by TheSharpieOne** [comment] 2018-03-19 20:23
The order of the class names does not matter; specificity matters.
See https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
Also see https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Cascade_and_inheritance

Duplicate of #423 
Duplicate of #882

**Closed by TheSharpieOne** 2018-03-19 20:23 UTC
