### ISSUE TITLE
Card issue - <div> appearing as descendant of <p>

### ISSUE THREAD

**Issue by owenashurst** [reactstrap/reactstrap#1611] opened 2019-09-01 12:13 UTC
- components: `Card`
- reactstrap version `^8.0.1`
- import method `import` 
- react version `^16.8.6`
- bootstrap version `^4.3.1`

### What is happening?

The card text element appears to be a paragraph when it should be a div.

![categories  card](https://user-images.githubusercontent.com/4403436/64076191-87bf7b80-ccb9-11e9-81f8-cc0c456ce5ac.PNG)

This issue then results in errors within the console.

### What should be happening?

The paragraph element should be a div.

![categories  card fix](https://user-images.githubusercontent.com/4403436/64076207-c9502680-ccb9-11e9-8ac2-6ba6c336b4b4.PNG)

### Steps to reproduce issue

1.) Create a new component using the Card component.
2.) Add a CardTitle and a CardText component. 
3.) Add text to the inner of the CardText component.

### Error message in console

```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by InputGroupAddon)
    in InputGroupAddon (at sidebar-right-widgets.js:26)
    in div (created by InputGroup)
    in InputGroup (at sidebar-right-widgets.js:24)
    in p (created by CardText)
    in CardText (at sidebar-right-widgets.js:23)
    in div (created by CardBody)
    in CardBody (at sidebar-right-widgets.js:21)
    in div (created by Card)
    in Card (at sidebar-right-widgets.js:20)
    in div (created by Col)
    in Col (at sidebar-right-widgets.js:19)
    in SidebarRightWidgets (at main.js:22)
    in div (created by Row)
    in Row (at main.js:18)
    in div (created by Container)
    in Container (at main.js:17)
    in div (at main.js:16)
    in Main (at app.js:15)
    in Router (at app.js:13)
    in App (at src/index.js:7)
```

### Code

Create a new component with the following;

```
<Card className="my-4">
    <CardBody>
        <CardTitle>Categories</CardTitle>
        <CardText>
            <Col lg="12" className="text-center">
                Category links...
            </Col>
        </CardText>
    </CardBody>
</Card>
```

**Comment by TheSharpieOne** [comment] 2019-09-03 14:32
By default, `CardText` will output `<p>` tags. This is done as it is the most common use-case (putting text within `CardText`).

If you want it to output another HTML tag, use the `tag` prop:
```jsx
<Card className="my-4">
    <CardBody>
        <CardTitle>Categories</CardTitle>
        <CardText tag="div">
            <Col lg="12" className="text-center">
                Category links...
            </Col>
        </CardText>
    </CardBody>
</Card>
```

You also might want to consider not using `CardText` if you are using Layout components (or maybe change the structure so that `<CardText>` is within `<Col>`):
```jsx
<Card className="my-4">
    <CardBody>
        <CardTitle>Categories</CardTitle>
          <Col lg="12" className="text-center">
              Category links...
          </Col>
    </CardBody>
</Card>
```

**Comment by owenashurst** [comment] 2019-09-03 21:03
Thanks @TheSharpieOne. Didn't know the tags property could be used for that. Only ever used it to specify "Link" from react-router for NavLink's.

**Comment by TheSharpieOne** [comment] 2019-09-30 17:28
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2019-09-30 17:28 UTC
