### ISSUE TITLE
data-loading-text on <Button />

### ISSUE THREAD

**Issue by Kielan** [reactstrap/reactstrap#867] opened 2018-02-26 15:44 UTC
### Issue description

- components: `Button`
- reactstrap version `latest`

### Feature
It would be nice to be able to control reactstrap buttons properly as ladda buttons, a common practice in bootstrap development, looks like this lib doesn't have it

https://github.com/hakimel/Ladda

Can we come to agreement that this is an improvement that needs a pull request? I will provide

**Comment by TheSharpieOne** [comment] 2018-02-26 16:03
This library aims to be a react replacement for bootstrap.js (since bootstrap.js is jquery based and doesn't play too nice with react). If it's not in bootstrap, it's not in reactstrap.
There is [react-ladda](https://github.com/jsdir/react-ladda), but ladda itself doesn't have a way to swap the text so neither does react-ladda.
You can use react-ladda with reactstrap, but since they both style a button, I wouldn't suggest using them together (just use react-ladda). See https://stackblitz.com/edit/reactstrap-v5beta-ladda?file=Example.js for how they would be used together and how it looks (note the color it set to primary, but ladda's color is used)
All that being said, you can create you own package with this feature and publish it. I have done something similar with other "reactstrap features" which do not fit into bootstrap and thus do not belong in reactstrap (such as [availity-reactstrap-validation](https://github.com/Availity/availity-reactstrap-validation)). If you go down this path, let me know so that we can link to it in the readme (or make a PR to add that link yourself).

**Comment by TheSharpieOne** [comment] 2018-04-18 17:33
I'm closing this since the the issue is no longer active and it appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2018-04-18 17:33 UTC
Labels: not a bug/out of scope

**Comment by GoPro16** [comment] 2019-05-02 01:21
@TheSharpieOne just look at this and it seems it was created before spinners were implemented in bootstrap 4. I was able to create a working example with the bootstrap 4 spinner and button to create a "loading" button which can just be a `loading` prop on the button. I am sure I am not doing the styling 100% correct but wanted to get your input on it if its worth getting implemented into the lib or if its completely out of scope. 

I know this library doesn't talk to bootstrap directly and since we can't access the sass variables in bootstrap they would have to be hardcoded and change on bootstrap 4 updates unless there is some other styling way we can achieve the same thing.

https://codesandbox.io/s/54v6zm886k

<img width="568" alt="Screen Shot 2019-05-01 at 9 20 48 PM" src="https://user-images.githubusercontent.com/14143881/57052704-08606380-6c57-11e9-87e0-20684feace4f.png">
