### ISSUE TITLE
reactstrap Alert Component timeout leave is not work 

### ISSUE THREAD

**Issue by cunwenWang** [reactstrap/reactstrap#401] opened 2017-04-23 07:09 UTC
`transitionAppearTimeout: PropTypes.number, `
`transitionEnterTimeout: PropTypes.number,` 
`transitionLeaveTimeout: PropTypes.number`
this is my code 
`
<Alert
          color={color} isOpen={this.state.visible}
          toggle={this.onDismiss} transitionAppearTimeout={150}
          transitionLeaveTimeout={150} transitionEnterTimeout={150}
        >
          <strong>{message}</strong>
        </Alert>
`
after 150ms , it does not leave

**Comment by senseluo** [comment] 2017-05-14 03:41
I am guessing Alert will not dismiss automatically for now, all *timeout props here should be derived from [ReactCSSTransitionGroup](https://facebook.github.io/react/docs/animation.html) which is only about animation when component mount/unmount.

**Comment by mkalish** [comment] 2017-07-06 18:03
@cunwenWang `transitionLeaveTimeout` dictates it how long the element should animate when its being removed from the DOM.  If you want to have the alert removed after a 150ms, you'll need to set a timeout for 150ms that calls `this.setState({visible: false})`

**Comment by TheSharpieOne** [comment] 2017-08-01 20:52
@cunwenWang did the replies from senseluo and mkalish answer your question? If not, can you clarify what you expect to happen and what is actually happening?

**Comment by TheSharpieOne** [comment] 2017-11-16 04:54
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2017-11-16 04:54 UTC

**Comment by harishmahajan** [comment] 2018-02-06 12:15
please install this npm i react-transition-group --save
