### ISSUE TITLE
UncontrolledDropdown in right end of Navbar out of screen

### ISSUE THREAD

**Issue by shaozi** [reactstrap/reactstrap#920] opened 2018-03-20 22:39 UTC
### Issue description

- components: `UncontrolledDropdown`
- reactstrap version `5.0.0-beta.2`
- import method `es`
- react version `16.2.0`
- bootstrap version `4.0.0`

### What is happening?
Using the first example of Navbar in the web document. The dropdown menu displayed outside of the right side of the web page. 

```
+------------------------------------------------------------------------------+
| Navbar                                                              Dropdown |
+------------------------------------------------------------------- /\-----------------+
                                                                    |  item1            |
                                                                    |  item2            |
                                                                    +-------------------+

```
### What should be happening?

It should look like this:

```
+------------------------------------------------------------------------------+
| Navbar                                                              Dropdown |
+---------------------------------------------------------|---------- /\-------|
                                                          |  item1             |
                                                          |  item2             |
                                                          +--------------------+
```

At the edge of the page, the dropdown menu should move to the left to completely stay in the page.

### Steps to reproduce issue

Copy and paste the first example of the Navbar and see the dropdown menu

You can also see it in the example page itself. The dropdown's right side is out of the navbar's right side.

**Comment by shaozi** [comment] 2018-03-21 18:03
Added a `right` in `<DropdownMenu>` worked.

**Comment by TheSharpieOne** [comment] 2018-03-23 19:14
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2018-03-23 19:14 UTC

**Comment by nora-sch** [comment] 2023-07-05 10:48
It doesn't work now. Can't find the class to add for move dropdown to the left side

**Comment by aniket-solulab** [comment] 2024-01-31 14:28
its still an issue
