### ISSUE TITLE
Relationship to react-bootstrap and react-bootstrap-4

### ISSUE THREAD

**Issue by james-s-turner** [reactstrap/reactstrap#58] opened 2016-07-27 13:22 UTC
Hi, I was wondering what are the pros and cons of this project versus react-bootstrap and react-bootstrap-4 (a temporary fork for bootstrap 4). It would be great to have a short statement as part of the intro.

**Comment by eddywashere** [comment] 2016-07-28 04:18
Sort of a duplicate of https://github.com/reactstrap/reactstrap/issues/34

There are differences, but I don't think it's normal for projects to be responsible for noting differences between a similar project. I think users should do their own due diligence when deciding on a library. I think the docs, the source code and the project goals in the readme should help with that.  Consider trying a simple example with both projects. Then see if it's worth doing a more involved example. 

Feel free to open up an issue to describe what was lacking or any issues you come across.

**Closed** 2016-07-28 20:29 UTC
