### ISSUE TITLE
Don't want to load the whole lib if I only use 7-8 components

### ISSUE THREAD

**Issue by gtournie** [reactstrap/reactstrap#391] opened 2017-04-06 08:14 UTC
I use reactstrap in my project and I realized it was loading the entire lib, even when I use only 7-8 components. I thought they would be removed with the new Tree Shaking optimization in webpack 2, but it doesn't, because your dist is already compiled without this optimization.

So, at least could you include the src dir in the package please? This way I could import/compile them as I want (with es2015, { modules: false }) and only include the components I use. In my case we're speaking about getting rid of 20Ko gzipped.

**Comment by matteocng** [comment] 2017-04-06 10:34
This module publishes the file: `dist/reactstrap.es.js` for `ES2015`aware bundlers (`module` key in `package.json`). This file is transpiled to `ES5` and has native `ES2015` modules. Unfortunately `Webpack 2` has [some issues](https://github.com/webpack/webpack/issues/2867) with tree shaking, `Rollup` may do a better job.

This works with `Webpack 2`:

```js
import Button from 'reactstrap/lib/Button'
```
But the files in `lib` are transpiled with `transform-es2015-modules-commonjs`, so they use `CommonJS` internally.

Maybe we could publish a `module` directory (`ES5` + `ES2015` modules) and then either write:

```js
import Button from 'reactstrap/module/Button'
```

... or use [babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports).

This is one way it can be done by just modifying `package.json`:

```diff
diff --git a/package.json b/package.json
index 8d6d9a6..f915e48 100644
--- a/package.json
+++ b/package.json
@@ -12,7 +12,9 @@
     "start": "BABEL_ENV=webpack webpack-dev-server --config ./webpack.dev.config.js --watch",
     "build-docs": "cross-env WEBPACK_BUILD=production webpack --config ./webpack.dev.config.js --progress --colors",
     "build": "cross-env NODE_ENV=production rollup -c",
-    "prebuild": "BABEL_ENV=dist-dir babel src --out-dir lib --ignore src/__tests__/",
+    "prebuild": "npm run build:lib && npm run build:module",
+    "build:lib": "BABEL_ENV=dist-dir babel src --out-dir lib --ignore src/__tests__/",
+    "build:module": "BABEL_ENV=module-dir babel src --out-dir module --ignore src/__tests__/",
     "create-release": "npm test && sh ./scripts/release",
     "publish-release": "npm test && sh ./scripts/publish",
     "lint": "eslint src"
@@ -25,8 +27,9 @@
     "LICENSE",
     "README.md",
     "CHANGELOG.md",
+    "dist",
     "lib",
-    "dist"
+    "module"
   ],
   "keywords": [
     "reactstrap",
```

**Comment by cr101** [comment] 2017-04-07 02:55
[Create-React-App](https://github.com/facebookincubator/create-react-app/pull/1291) will also support tree shaking in case anyone is using CRA

**Comment by TheSharpieOne** [comment] 2017-07-25 16:52
As stated above, this library exposes both an esModules and a commonjs way of importing individual components. There is also an open issue in Webpack 2 for tree shaking not working, which would be the root cause.

@gtournie does the suggested ways (mentioned above) of importing specific modules resolve your issue?

**Comment by cr101** [comment] 2017-07-25 20:35
[Webpack 3.4](https://github.com/webpack/webpack/releases) has been released, maybe that will help with tree shaking.

**Comment by TheSharpieOne** [comment] 2017-09-15 22:45
I'm closing this as this library provides many way to import things and is doing everything it can to make this happen.
If you feel there is more to add, comment and I will reopen.

**Closed by TheSharpieOne** 2017-09-15 22:45 UTC

**Comment by jkrehm** [comment] 2018-04-09 16:30
I know this is an old, closed ticket, but the issue seems to persist with Webpack 4. I believe it's more of an issue with UglifyJS, though, because Webpack is correctly marking the `export`s as unused, which should allow UglifyJS to remove the un-exported code (since it's unused). Unfortunately that part is not working because lines like `Navbar.propTypes = propTypes$3;` cause UglifyJS to think that the component is still in use. I don't know what the solution is, but it is a frustration to have the entire library includes when I only use a handful of component.

**Comment by jkrehm** [comment] 2018-04-11 22:10
FYI, UglifyJS v3.3.12 and up seems to work correctly. Prior to that, there was some bug (not sure what) that made it so this would have the unused code removed:
```
var Navbar = function() { ... };
Navbar.propTypes = {};
```
but this would not:
```
var Navbar = function() { ... };
Navbar.propTypes = {};
Navbar.defaultProps = {};
```
Unfortunately, Webpack 4 uses UglifyJS's `harmony` branch (`uglify-es`) and that branch is largely unmaintained right now, so the bug fix has not been brought over from `uglify-js`.

**Comment by johnunclesam** [comment] 2018-04-16 00:27
Any chance I can use this way of importing ReactStrap?

```js
import {
  UncontrolledDropdown,
  DropdownToggle
} from "reactstrap";
```

without importing all the entire package?

I'm using latest `create-react-app`.

What to do?

**Comment by TheSharpieOne** [comment] 2018-04-16 13:52
If tree shaking isn't working properly in your bundling tool, the only option is to import the individual files via:
```js
import UncontrolledDropdown from 'reactstrap/lib/UncontrolledDropdown';
import DropdownToggle from 'reactstrap/lib/DropdownToggle';
```

**Comment by janimo** [comment] 2018-10-12 15:49
Is there a bundling tool where tree shaking works well for reactstrap? When using CRA 2 with default settings one still needs to import individual files as in the last comment.
