### ISSUE TITLE
Lastest React warns of manually calling Proptypes validation.

### ISSUE THREAD

**Issue by jsarman** [reactstrap/reactstrap#96] opened 2016-08-09 16:27 UTC
React 15.3  now warns when using Proptypes validation in code.
Warning: You are manually calling a React.PropTypes validation function for the `xs` prop on `Col`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by TheSharpieOne** [comment] 2016-08-11 14:59
I am not seeing any PropTypes being manually called. The PropTypes for [`xs` on `col`](https://github.com/reactstrap/reactstrap/blob/master/src/Col.jsx#L19) are only referenced, never called.

The difference being `PropTypes.string` is a reference to the function and `PropTypes.string()` calls the function. Same with `columnProps` in the Col code. It is a reference to a series of references which in turn have more references, none of which are actually called in the Col code. `shape` and `oneOfType` are called, but they are just passed parameters to be used with the validation. They return a reference to a function which is the actual validation function; that function is just passed around and never manually called within this project's code.

In the link you posted, the 'bad' example shows where `apiShape` is a reference to some validations and is actually being called via `var error = apiShape(json, 'response');`.
The reason this will break things in the future is because the functions these validations reference will be removed from the production code (so validation would only really happen in development)

**Comment by eddywashere** [comment] 2016-08-13 15:30
I'm also not seeing that issue with 15.3. Are there any steps to reproduce? I added a grid example to the demo - http://codepen.io/eddywashere/pen/ZOjmkm

**Comment by eddywashere** [comment] 2016-09-06 07:09
Closing this for now. Feel free to reopen with an example.

**Closed by eddywashere** 2016-09-06 07:10 UTC
Labels: needs-example
