### ISSUE TITLE
Clicking a button that closes a collapse too fast breaks it.

### ISSUE THREAD

**Issue by aericson** [reactstrap/reactstrap#251] opened 2016-12-12 22:18 UTC
### Clicking a button that opens/close a collapse will leave its state inconsistent.

- version `#3.8.1`
- components: `Collapse`

### Steps to reproduce issue
- Open the codepen http://codepen.io/anon/pen/WogLGo
- Double click the button with a very short interval between the two clicks.

**Comment by LiJinyao** [comment] 2016-12-13 16:40
I checked out your code. The state isn't  inconsistent **in the Collapse component**, when the component is collapsing, it will ignore the isOpen prop change (I think bootstrap do the same thing for better user experience).  
There is no proper way to determining  the real state of that component.
I think we need a callback function to do that.

**Comment by aericson** [comment] 2016-12-13 17:03
I think the problem is the `setTimeout` [here](https://github.com/reactstrap/reactstrap/blob/master/src/Collapse.js#L42-L47). By the time it changes the state, it has already changed.

Didn't spend much time debugging it, but can't we `clearTimeout` if `isOpen` changes?

**Comment by LiJinyao** [comment] 2016-12-13 17:37
Yes is is another way to do it. But if we `clearTimeout` when `isOpen` changes, It will break the current animation. So the problem is should we allow break the collapsing? bootstrap choice not allow change state when collapsing ([see here](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L114-L117)), maybe we should keep the same.

**Comment by CoderJoeIO** [comment] 2017-01-28 18:31
I'm having a problem with this issue now, should it not just block state when while collapsing as you mentioned? To do this at my higher component level I would need a callback to tell me when the transition is complete. Unless there is a better idea?

**Comment by TheSharpieOne** [comment] 2017-11-16 04:53
fixed in v5 alpha

**Closed by TheSharpieOne** 2017-11-16 04:53 UTC
