### ISSUE TITLE
Responsive display component for showing and hiding elements?

### ISSUE THREAD

**Issue by Woile** [reactstrap/reactstrap#667] opened 2017-10-31 17:43 UTC
Hey guys I was wondering if there is a recommended way to [hide responsive elements like in bootstrap](http://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements). 
It would be cool to have something similar to [material-ui layout](https://material-ui-next.com/layout/hidden/) but if that's not possible, maybe point me out how to achieve this.

It may also be helpful if it were included in the documentation.

Thank you!!

**Comment by TheSharpieOne** [comment] 2017-10-31 18:22
Currently you have to add the classes yourself using `className`. Since these classes can be applied to any component/element there is not a nice way to add them to any particular component. #81 discusses a way for reactstrap to provide that.

**Comment by Woile** [comment] 2017-10-31 18:25
But wouldn't that render the elements and hide them, instead of preventing them from appearing?

I've found this library, I think I'll go with it:

https://github.com/contra/react-responsive#common-use-cases

**Comment by TheSharpieOne** [comment] 2017-10-31 18:30
This is how bootstrap v4 currently works and reactstrap is the react version of bootstrap v4. Reactstrap provides the features and functionality of bootstrap.js but using react and without jquery. Other components just apply the classes for you for convenience.

**Comment by TheSharpieOne** [comment] 2017-11-21 10:38
I'm closing this since the the issue is no longer active and it appear it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered

**Closed by TheSharpieOne** 2017-11-21 10:38 UTC
Labels: question

**Comment by DurgaPammi** [comment] 2018-04-09 09:14
hi,
can u tell me how to hide the components in react js,in my project when we click on button i need to show few components and hide few components.

how to resolve this issue.??

**Comment by shakeelkoper** [comment] 2018-07-30 06:41
Hi,

There is another nice things I found 
https://goshakkk.name/different-mobile-desktop-tablet-layouts-react/
