### ISSUE TITLE
Can't add Tag to ListGroupItem

### ISSUE THREAD

**Issue by lednhatkhanh** [reactstrap/reactstrap#238] opened 2016-11-28 03:23 UTC
```
import {Button, Tag, ListGroupItem, ListGroupItemHeading, ListGroupItemText} from 'reactstrap';

<ListGroupItem action>
                <ListGroupItemHeading>{task.name}</ListGroupItemHeading>
                <ListGroupItemText>
                    {moment(task.createdAt).format('MMM Do YY')}
                </ListGroupItemText>
                <Tag color="danger" pill className="float-xs-right">Delete</Tag>
            </ListGroupItem>
```

And here's the error message: 

`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method`

I want something like this:
[Tags](https://v4-alpha.getbootstrap.com/components/list-group/#tags)

Thank you.

**Comment by LiJinyao** [comment] 2016-11-28 04:03
Oh, Your code works in my doc ( not merged yet), is this what you want ?
![screen shot 2016-11-28 at 11 55 19 am](https://cloud.githubusercontent.com/assets/3450595/20655847/90807f48-b561-11e6-8404-b02accc2040a.png)

Here is the code, I moved the tag into the ListGroupItemText to prevent the style issue showed in the second picture.
```
<ListGroupItem action>
    <ListGroupItemHeading>taskName</ListGroupItemHeading>
    <ListGroupItemText>
        Task
        <Tag color="danger" pill className="float-xs-right">Delete</Tag>
    </ListGroupItemText>
</ListGroupItem>
```
Here is the style issue when put Tag outside the ListGroupItemText
![screen shot 2016-11-28 at 11 56 56 am](https://cloud.githubusercontent.com/assets/3450595/20655905/17259952-b562-11e6-9d50-582d13d279ca.png)
```
<ListGroupItem action>
    <ListGroupItemHeading>taskName</ListGroupItemHeading>
    <ListGroupItemText>
        Task      
    </ListGroupItemText>
    <Tag color="danger" pill className="float-xs-right">Delete</Tag>
</ListGroupItem>
```
I hope this may help you:)

**Comment by lednhatkhanh** [comment] 2016-11-28 04:13
It's super weird! I doesn't work in my code :(. First I though that I made a typo, but even when I copy-paste your code, it still doesn't work. I don't know, I'm using React with Meteor, not with Webpack, maybe there are some problem with it tho...

**Comment by LiJinyao** [comment] 2016-12-13 17:08
After working with bootstrap alpha 6, I found the problem is in alpha 6, the component `Tag` is renamed to `Badge`. So are you using v4 branch? This component is broken and got same problem in v4 branch.

**Comment by tutuca** [comment] 2016-12-22 15:34
Is the alpha 6 available in someway?

**Comment by eddywashere** [comment] 2017-01-03 03:54
@tutuca you can npm install a git revision like, `npm install twbs/bootstrap#12345` but you'll have to import the css via your build tooling of choice or copy over the latest files from dist, https://github.com/twbs/bootstrap/tree/v4-dev/dist.

closing this out. reopen with more info, (which alpha release of reactstrap) and demo.

**Closed by eddywashere** 2017-01-03 03:54 UTC
