### ISSUE TITLE
cant find doc on forms

### ISSUE THREAD

**Issue by crap-coder** [reactstrap/reactstrap#1336] opened 2018-12-24 20:58 UTC
i cant visit the "form" component's page on the doc . somehow the page is down

**Comment by saleem-git** [comment] 2018-12-27 12:16
Its been down for days, can someone please look into this, project deadline closing in.

**Comment by Xachman** [comment] 2018-12-27 15:21
Xachman@11d9f1a

The issue is with the plaintext attribute. I dont have time to write a unit test for this right now so I cannot create a PR for this change now. But if you are working locally and would like to read the docs you can either remove the plaintext input or use this update.

**Comment by TheSharpieOne** [comment] 2018-12-31 23:10
Fixed.

**Closed by TheSharpieOne** 2018-12-31 23:10 UTC
