### ISSUE TITLE
FormFeedback not showing when put after InputGroup

### ISSUE THREAD

**Issue by yoones** [reactstrap/reactstrap#1625] opened 2019-09-14 15:36 UTC
- components: `FormFeedback`
- reactstrap version `#8.0.1`
- import method `es`
- react version `#16.9.0`
- bootstrap version `#4.3.1`

### What is happening?

FormFeedback after an Input component displays error message when the input is invalid.
FormFeedback after an InputGroup component does not display error message when the input inside InputGroup is invalid.

### What should be happening?

FormFeedback should show up when following an InputGroup which contains an invalid Input.

### Code

    <Form>
      <FormGroup>
        <InputGroup>
          <Input name="name" className="is-invalid" />
          <InputGroupAddon addonType="append">
            <Button type="submit">+</Button>
          </InputGroupAddon>
        </InputGroup>
        <FormFeedback>This error should show up but is not.</FormFeedback>
      </FormGroup>
    </Form>

**Comment by TheSharpieOne** [comment] 2019-09-17 16:02
Duplicate of #1619

The FormFeedback must be next to the input. Also, I don't believe bootstrap supports having an addon to the right of the input _and_ feedback.
As also noted in #1619, you can control the `d-block` class to force it to show.

**Closed by TheSharpieOne** 2019-09-17 16:02 UTC

**Comment by pavolhudran** [comment] 2023-11-24 11:18
Here's a solution using the InputGroup extension from ReactStrap:

```
import React from 'react';
import { InputGroup as ReactstrapInputGroup, Input, InputGroupProps } from 'reactstrap';

export const InputGroup: React.FC<InputGroupProps> = ({ children, ...props }) => {
  const isAnyInvalid = React.Children.toArray(children).some((child) => {
    if (React.isValidElement(child) && (child.type as unknown) === Input) {
      const inputProps = child.props as Record<string, unknown>;
      return inputProps.invalid;
    }
    return false;
  });

  const inputGroupClassName = `${props.className || ''} ${isAnyInvalid ? 'is-invalid' : ''}`.trim();

  return (
    <ReactstrapInputGroup {...props} className={inputGroupClassName}>
      {children}
    </ReactstrapInputGroup>
  );
};
```

And styles with SCSS:

```
.input-group {
    &.is-invalid {
      .form-control,
      .custom-select,
      .input-group-text,
      .input-group-append, /* fallback for Bootstrap 4 */
      .input-group-append > .input-group-text /* fallback for Bootstrap 4 */ {
        border-color: $danger !important;
      }
    }
}
```
